const questionsOX = [
  // コーヒーの歴史・伝播 (10 questions) - 5T, 5F
  { id: 'ox-001', category: '生豆', question: 'コーヒーの原産地はエチオピアのカッファ地方である。', answer: true, difficulty: 1, explanation: 'コーヒーノキはエチオピア西部のカッファ地方に自生。「コーヒー」の語源も「カッファ」が転訛したとされている。' },
  { id: 'ox-002', category: '生豆', question: 'noble treeはパリ植物園で育てられた苗が起源である。', answer: false, difficulty: 2, explanation: 'noble treeはアムステルダムの植物園で育てられた苗が起源。その後フランス国王ルイ14世に贈られた。' },
  { id: 'ox-003', category: '生豆', question: '世界初のコーヒーハウス「カーヴェハーネ」は1554年イスタンブールで開業した。', answer: true, difficulty: 1, explanation: '1554年、オスマン帝国のイスタンブールに世界初のコーヒーハウスが開業した。' },
  { id: 'ox-004', category: '生豆', question: 'ヨーロッパ最初のコーヒーハウスはロンドンで1650年に開業した。', answer: false, difficulty: 2, explanation: 'ヨーロッパ最初のコーヒーハウスはベネチア（イタリア）で1645年に開業。イギリス最初はオックスフォードで1650年。' },
  { id: 'ox-005', category: '生豆', question: 'ブルボン品種の名前の由来はブルボン島（現レユニオン島）である。', answer: true, difficulty: 2, explanation: 'ティピカの突然変異として生まれたブルボン品種は、フランス領ブルボン島で栽培開始されたことから命名。' },
  { id: 'ox-006', category: '生豆', question: 'ラーゼスは12世紀にコーヒーについて医学集成で記述した。', answer: false, difficulty: 2, explanation: 'ラーゼスはアラビアの医師で、900年頃（9〜10世紀）に医学集成で「bunchum」として記述した。' },
  { id: 'ox-007', category: '生豆', question: '日本初の珈琲店「可否茶館」は1888年4月13日に東京・上野で開業した。', answer: true, difficulty: 1, explanation: '鄭永慶により1888年（明治21年）4月13日に東京・上野に開業。4月13日は現在「喫茶店の日」。' },
  { id: 'ox-008', category: '生豆', question: 'カネフォラ種（ロブスタ）はアフリカのコンゴで1898年に発見された。', answer: true, difficulty: 1, explanation: 'ベルギーの植物学者エミール・ローランがアフリカのコンゴで1898年に発見。' },
  { id: 'ox-009', category: '焙煎', question: 'オスマン帝国がコーヒー貿易で輸出したのは焙煎豆のみで、生きた種子・苗木は持ち出しを禁止していた。', answer: true, difficulty: 2, explanation: 'オスマン帝国はコーヒーの国際競争力維持のため、焙煎豆のみを輸出し、生きた種子・苗木の持ち出しを禁止（死罪）していた。' },
  { id: 'ox-010', category: '生豆', question: 'ロンドンのコーヒーハウスは「ペニー大学」と呼ばれ、1ペニーで利用できた。', answer: false, difficulty: 2, explanation: '1652年のロンドンのコーヒーハウスは1ペニーで利用でき、誰もが気軽に知識を得られることから「ペニー大学」と呼ばれた。実際の説は異なる。' },

  // 植物学的分類・品種 (15 questions) - 8T, 7F
  { id: 'ox-011', category: '風味からコーヒーを理解する', question: 'アラビカ種は他家受粉で繁殖する。', answer: false, difficulty: 1, explanation: 'アラビカ種は自家受粉（自家稔性）で繁殖。カネフォラ種が他家受粉（自家不稔性）。' },
  { id: 'ox-012', category: '風味からコーヒーを理解する', question: 'コーヒーノキの属はコフィア属である。', answer: true, difficulty: 1, explanation: 'コーヒーノキはアカネ目→アカネ科→コーヒーノキ属（コフィア属）に分類される。' },
  { id: 'ox-013', category: '風味からコーヒーを理解する', question: 'カネフォラ種のカフェイン含有量はアラビカ種の約2倍である。', answer: true, difficulty: 2, explanation: 'アラビカ種0.8〜1.4%、カネフォラ種1.7〜4%。カネフォラ種が約2倍高い。' },
  { id: 'ox-014', category: '風味からコーヒーを理解する', question: 'ティピカ品種はアラビカ種の原型である。', answer: true, difficulty: 1, explanation: 'ティピカはアラビカ種の原型で、noble treeもティピカ系。世界に伝播した主要品種。' },
  { id: 'ox-015', category: '風味からコーヒーを理解する', question: 'アラビカ種は2倍体で染色体数は22本である。', answer: false, difficulty: 2, explanation: 'アラビカ種は4倍体で染色体数は44本。カネフォラ種が2倍体で22本。' },
  { id: 'ox-016', category: '風味からコーヒーを理解する', question: 'カトゥーラはブルボンの突然変異から生まれた品種である。', answer: true, difficulty: 2, explanation: 'カトゥーラはブルボンの突然変異で、1935年ブラジルで発見。矮小種で収量が多い。' },
  { id: 'ox-017', category: '風味からコーヒーを理解する', question: 'ゲイシャ品種はパナマが原産地である。', answer: false, difficulty: 2, explanation: 'ゲイシャ品種はエチオピア・ゲシャ村が原産地。パナマで高品質として再注目された。' },
  { id: 'ox-018', category: '生豆', question: 'SL28とSL34はケニアのスコット農業研究所で選抜された品種である。', answer: true, difficulty: 2, explanation: 'SL28・SL34はケニアのスコット農業研究所（Scott Laboratory）で選抜されたさび病耐性品種。' },
  { id: 'ox-019', category: '風味からコーヒーを理解する', question: 'ピーベリーはコーヒーチェリーの約30%に見られる丸い豆である。', answer: false, difficulty: 2, explanation: 'ピーベリーの混入率は5〜20%。30%は多すぎる。' },
  { id: 'ox-020', category: '風味からコーヒーを理解する', question: 'コーヒーチェリーの構造は外側から外皮・果肉・ミューシレージ・パーチメント・シルバースキン・種子である。', answer: true, difficulty: 2, explanation: 'コーヒーチェリーは6層構造で外側から：外皮→果肉→ミューシレージ→パーチメント→シルバースキン→種子の順。' },
  { id: 'ox-021', category: '風味からコーヒーを理解する', question: 'ムンドノーボはカトゥーラ×ブルボンの交配品種である。', answer: false, difficulty: 2, explanation: 'ムンドノーボはティピカ×ブルボンの交配品種。カトゥアイがカトゥーラ×ムンドノーボ。' },
  { id: 'ox-022', category: '風味からコーヒーを理解する', question: 'ヒブリドティモール（HdT）はアラビカ×カネフォラの交配品種である。', answer: true, difficulty: 2, explanation: 'ヒブリドティモールはアラビカ×カネフォラの偶発的交配品種で、カネフォラの病害抵抗性を持つ。' },
  { id: 'ox-023', category: '風味からコーヒーを理解する', question: 'マラゴジッペはティピカの突然変異で豆が大粒である。', answer: true, difficulty: 1, explanation: 'マラゴジッペはティピカの突然変異で豆が大粒（エレファントビーン）。ブラジル・マラゴジッペ市で発見。' },
  { id: 'ox-024', category: '生豆', question: 'アラビカ種の少糖類含有量はカネフォラ種より高い。', answer: true, difficulty: 2, explanation: 'アラビカ種6〜9%、カネフォラ種3〜7%。アラビカ種の方が甘み成分が豊富。' },
  { id: 'ox-025', category: '風味からコーヒーを理解する', question: 'コーヒーノキ属には約10種が商業的に流通している。', answer: false, difficulty: 2, explanation: 'コーヒーノキ属には100種以上が確認されているが、商業的に流通するのは主に2種（アラビカ・カネフォラ）。' },

  // 栽培・土壌・病害虫 (15 questions) - 8T, 7F
  { id: 'ox-026', category: '生豆', question: 'コーヒーベルトは南北回帰線の間（北緯25度〜南緯25度）である。', answer: true, difficulty: 1, explanation: 'コーヒーベルトは赤道を挟む南北回帰線（北緯25度〜南緯25度）の間が主要栽培帯。' },
  { id: 'ox-027', category: '生豆', question: 'アラビカ種の最適標高は1,000〜1,500mである。', answer: false, difficulty: 1, explanation: 'アラビカ種の標高は900〜2,000mの範囲。1,000〜1,500mは一部に過ぎない。' },
  { id: 'ox-028', category: '生豆', question: 'アラビカ種に適した土壌の5条件には耕しやすさ・深さ・排水性・肥沃さ・腐植量が含まれる。', answer: true, difficulty: 2, explanation: '5条件：①耕しやすさ（作業性）②土壌の深さ③排水性④肥沃さ⑤腐植の量' },
  { id: 'ox-029', category: '生豆', question: '火山性土壌はコーヒー栽培に適している。理由は排水性が良く、ミネラルが豊富だからである。', answer: true, difficulty: 2, explanation: '火山性土壌はリン・カリウムなどのミネラルが豊富で、排水性と保水性のバランスも良い。' },
  { id: 'ox-030', category: '生豆', question: 'コーヒーさび病は1869年ブラジルで大流行した。', answer: false, difficulty: 2, explanation: 'コーヒーさび病は1869年セイロン島（スリランカ）で大流行（セイロン事件）。ブラジルではない。' },
  { id: 'ox-031', category: '生豆', question: 'コーヒーさび病により1890年までにセイロンの栽培面積の約90%が放棄された。', answer: true, difficulty: 2, explanation: 'セイロン事件：1869年流行→1886年までに輸出量80%減→1890年までに栽培面積90%放棄→紅茶へ転換。' },
  { id: 'ox-032', category: '生豆', question: 'シェードツリーとしてはバナナが最も一般的である。', answer: false, difficulty: 2, explanation: 'シェードツリーとして最も一般的なのはマメ科の樹木（窒素固定木）。バナナは初期の仮設日陰として使用。' },
  { id: 'ox-033', category: '生豆', question: 'コーヒー実穿孔虫（CBB）は世界最大のコーヒー害虫である。', answer: true, difficulty: 2, explanation: 'コーヒー実穿孔虫（Coffee Berry Borer / Hypothenemus hampei）は世界最大のコーヒー害虫で年間5億ドル以上の経済的損失。' },
  { id: 'ox-034', category: '生豆', question: 'コーヒー炭疽病（CBD）は世界中で被害が大きい。', answer: false, difficulty: 2, explanation: 'コーヒー炭疽病は主にアフリカで深刻。ヨーロッパやアジアでは被害が限定的。' },
  { id: 'ox-035', category: '風味からコーヒーを理解する', question: 'コーヒーノキの初開花は定植後2〜4年である。', answer: true, difficulty: 1, explanation: 'コーヒーノキのライフサイクル：定植後2〜4年で初開花が始まる。' },
  { id: 'ox-036', category: '生豆', question: '標高が高いほど、コーヒー豆の成熟がゆっくり進み風味成分が蓄積される。', answer: true, difficulty: 2, explanation: '標高が高い→日較差が大きい→成熟が遅い→風味成分が多く蓄積。高地産ほど硬く酸味・風味が豊か。' },
  { id: 'ox-037', category: '焙煎', question: 'クロロゲン酸はコーヒーの苦味・渋味の元である。', answer: true, difficulty: 2, explanation: 'クロロゲン酸はポリフェノールで、生豆では6〜9%含有。焙煎で一部分解される。' },
  { id: 'ox-038', category: '生豆', question: 'アラビカ種の最適気温は年平均18〜22℃である。', answer: true, difficulty: 1, explanation: 'アラビカ種の気温：年平均15〜25℃、最適18〜22℃。' },
  { id: 'ox-039', category: '生豆', question: 'コーヒーさび病の対策として銀系殺菌剤が有効である。', answer: false, difficulty: 2, explanation: 'さび病対策は銅系殺菌剤が有効。銀系ではなく銅系が使用される。' },
  { id: 'ox-040', category: '風味からコーヒーを理解する', question: 'カティモールはカトゥーラ×ヒブリドティモールの交配品種でさび病に強い。', answer: true, difficulty: 2, explanation: 'カティモールはカトゥーラ×ヒブリドティモールの交配品種で、カネフォラの病害抵抗性を持つ。' },

  // 収穫方法 (10 questions) - 5T, 5F
  { id: 'ox-041', category: '風味からコーヒーを理解する', question: 'ピッキング方法では同じ畑を複数回巡回して完熟チェリーだけを選んで摘む。', answer: true, difficulty: 1, explanation: 'ピッキング（セレクティブ・ピッキング）は成熟のばらつきに合わせて複数回巡回し、完熟チェリーのみを手で選んで摘む。' },
  { id: 'ox-042', category: '風味からコーヒーを理解する', question: 'ストリッピング方法は最もコストが高い。', answer: false, difficulty: 1, explanation: 'ストリッピングはピッキングに比べ大幅に低コスト・短時間。最も高コストはピッキング。' },
  { id: 'ox-043', category: '風味からコーヒーを理解する', question: 'コーヒーの開花は乾季後の降雨がトリガーとなる。', answer: true, difficulty: 2, explanation: 'コーヒーノキは乾季の後の降雨をきっかけに開花（降雨後約10〜14日で開花）。' },
  { id: 'ox-044', category: '風味からコーヒーを理解する', question: '機械収穫は急斜面・山岳地帯でも使用可能である。', answer: false, difficulty: 1, explanation: '機械収穫は平坦地でのみ使用可能。急斜面・山岳地帯では使用不可。' },
  { id: 'ox-045', category: '風味からコーヒーを理解する', question: 'ブラジルはストリッピング方法を採用している。', answer: true, difficulty: 2, explanation: 'ブラジルは平坦地の大規模農園でストリッピング（一斉摘み）を採用。' },
  { id: 'ox-046', category: '風味からコーヒーを理解する', question: 'アラビカ種はカネフォラ種より開花・成熟のタイミングが比較的揃いやすい。', answer: true, difficulty: 2, explanation: 'アラビカ種は開花・成熟のタイミングが揃いやすいためピッキングに適している。' },
  { id: 'ox-047', category: '風味からコーヒーを理解する', question: 'アラビカ種の開花から完熟までは約6〜9ヶ月である。', answer: true, difficulty: 1, explanation: 'アラビカ種の成熟期間は約6〜9ヶ月（高地では8〜9ヶ月）。' },
  { id: 'ox-048', category: '風味からコーヒーを理解する', question: '未熟チェリーは甘い風味を生む。', answer: false, difficulty: 2, explanation: '未熟チェリーは糖分が少なくクロロゲン酸が多いため、渋み・青臭さ・不快な酸味を生む。' },
  { id: 'ox-049', category: '風味からコーヒーを理解する', question: 'コロンビアは赤道付近のため年2回の収穫期を持つ。', answer: true, difficulty: 2, explanation: 'コロンビアは赤道付近のため、メインクロップ（10〜2月）とミタカ（3〜6月）の年2回収穫。' },
  { id: 'ox-050', category: '風味からコーヒーを理解する', question: 'ケニアの収穫時期は年1回である。', answer: false, difficulty: 2, explanation: 'ケニアは赤道直下のため年2回収穫：メイン3〜7月、フライ9〜12月。' },

  // 精選方法 (20 questions) - 10T, 10F
  { id: 'ox-051', category: '風味からコーヒーを理解する', question: '非水洗式は設備が不要で廃水も出ない方式である。', answer: true, difficulty: 1, explanation: '非水洗式（ナチュラル）はそのまま乾燥させるため設備が不要で廃水も出ない。' },
  { id: 'ox-052', category: '商品名からコーヒーを理解する', question: '水洗式は大量の水が必要である。', answer: true, difficulty: 1, explanation: '水洗式は水比重選別・発酵槽・水洗いで大量の水が必要。廃水問題も課題。' },
  { id: 'ox-053', category: '風味からコーヒーを理解する', question: 'パルプドナチュラル方法はミューシレージを完全に除去する。', answer: false, difficulty: 2, explanation: 'パルプドナチュラルはミューシレージを残したまま乾燥させる。除去は水洗式。' },
  { id: 'ox-054', category: '風味からコーヒーを理解する', question: 'スマトラ式は乾燥期間が短縮される特徴がある。', answer: true, difficulty: 2, explanation: 'スマトラ式は半生きの状態で脱殻するため乾燥期間が短縮（約3日）。ウォッシュドの1〜2週間と比較。' },
  { id: 'ox-055', category: '風味からコーヒーを理解する', question: 'ナチュラル精選では未成熟果実を乾燥前に取り除く必要がある。', answer: false, difficulty: 2, explanation: 'ナチュラル精選は未成熟果実を乾燥前に取り除けないが、パルプドナチュラルはパルパーで除去可能。' },
  { id: 'ox-056', category: '風味からコーヒーを理解する', question: 'ケニア式はダブルウォッシュド方式で非常にクリーンなカップになる。', answer: true, difficulty: 2, explanation: 'ケニア式は発酵→水洗い→再発酵→最終水洗いで非常にクリーンなカップになる。' },
  { id: 'ox-057', category: '風味からコーヒーを理解する', question: 'ハニーコーヒーのブラックはミューシレージの残存率が最も低い。', answer: false, difficulty: 2, explanation: 'ハニーコーヒーの残存率順：ブラック＞レッド＞イエロー＞ホワイト。ホワイトが最も低い。' },
  { id: 'ox-058', category: '風味からコーヒーを理解する', question: 'スマトラ式はミューシレージ付きのパーチメント状態で脱殻する。', answer: true, difficulty: 2, explanation: 'スマトラ式の特徴は半生きの状態（水分30〜35%）で脱殻すること。' },
  { id: 'ox-059', category: '風味からコーヒーを理解する', question: 'アナエロビック発酵は密閉タンクに酸素を充填する。', answer: false, difficulty: 2, explanation: 'アナエロビック発酵はCO₂を充填し酸素を遮断する。酸素ではなく二酸化炭素。' },
  { id: 'ox-060', category: '風味からコーヒーを理解する', question: 'カーボニックマセレーションはチェリーを丸ごと密閉容器に入れる。', answer: true, difficulty: 2, explanation: 'カーボニックマセレーションはチェリーが果肉付きのままで、CO₂を能動的に注入する方法。' },
  { id: 'ox-061', category: '風味からコーヒーを理解する', question: '非水洗式コーヒーは風味が淡白である。', answer: false, difficulty: 2, explanation: '非水洗式は果実の甘み・ボディが豊かな風味を生む。淡白なのは水洗式。' },
  { id: 'ox-062', category: '風味からコーヒーを理解する', question: 'ナチュラル精選の課題は乾燥に時間がかかることである。', answer: true, difficulty: 2, explanation: 'ナチュラル精選は乾燥に時間がかかり、腐敗リスクもある課題がある。' },
  { id: 'ox-063', category: '風味からコーヒーを理解する', question: 'ブラジルが開発地のパルプドナチュラル方法はコスタリカでも盛んである。', answer: true, difficulty: 2, explanation: 'パルプドナチュラルはブラジルが開発地だが、コスタリカでもハニープロセスとして盛んに実施。' },
  { id: 'ox-064', category: '風味からコーヒーを理解する', question: 'スマトラ式生豆は深緑色で形がいびつになりやすい。', answer: true, difficulty: 2, explanation: 'スマトラ式は半生きの状態で脱殻するため、生豆が独特の深緑色でいびつになりやすい。' },
  { id: 'ox-065', category: '風味からコーヒーを理解する', question: 'ウォッシュド精選により品質が均一化されやすい。', answer: true, difficulty: 1, explanation: '水洗式は水比重選別や発酵槽で異物・未熟豆を除去でき、品質が均一化されやすい。' },
  { id: 'ox-066', category: '風味からコーヒーを理解する', question: 'インドネシア・スマトラ島ではナチュラル精選が主流である。', answer: false, difficulty: 2, explanation: 'インドネシア・スマトラ島ではスマトラ式（ウェットハル / ギリンバサ）が独自方式。ナチュラルではない。' },
  { id: 'ox-067', category: '風味からコーヒーを理解する', question: 'コロンビアの水洗式はクリーンで明確な酸味が特徴である。', answer: true, difficulty: 2, explanation: '水洗式は未成熟果実を除去でき、クリーン・明確な酸味が特徴になる。' },
  { id: 'ox-068', category: '風味からコーヒーを理解する', question: 'ケニア式発酵は1回のみである。', answer: false, difficulty: 2, explanation: 'ケニア式（ダブルウォッシュド）は2回の発酵：①12〜24時間→②再度12〜24時間。' },
  { id: 'ox-069', category: '風味からコーヒーを理解する', question: 'イエメンはナチュラル精選を伝統的に採用している。', answer: true, difficulty: 2, explanation: 'イエメンは非水洗式（ナチュラル）で伝統的な天日乾燥を実施。' },
  { id: 'ox-070', category: '風味からコーヒーを理解する', question: 'エチオピアは水洗式のみを採用している。', answer: false, difficulty: 2, explanation: 'エチオピアは非水洗式と水洗式の両方を採用。地域や施設により異なる。' },

  // 選別方法 (10 questions) - 5T, 5F
  { id: 'ox-071', category: '商品名からコーヒーを理解する', question: '1スクリーンは1/64インチである。', answer: true, difficulty: 1, explanation: '1スクリーン = 1/64インチ ≒ 約0.4mm。スクリーン18 = 18/64インチ ≒ 約7.1mm。' },
  { id: 'ox-072', category: '商品名からコーヒーを理解する', question: 'コロンビアの格付けでSupremoはスクリーン18以上である。', answer: false, difficulty: 2, explanation: 'コロンビアSupremo = SC17以上、Excelso = SC14〜16。18以上ではなく17以上が正しい。' },
  { id: 'ox-073', category: '商品名からコーヒーを理解する', question: 'ブラジルの格付けでNo.1が最高品質である。', answer: false, difficulty: 2, explanation: 'ブラジルはNo.2が最高グレード。No.1は存在しない（完全無欠点は不可能という考え方）。' },
  { id: 'ox-074', category: '商品名からコーヒーを理解する', question: 'ケニアの格付けでAAはスクリーン17〜18である。', answer: true, difficulty: 2, explanation: 'ケニアAA = SC17〜18（7.22mm以上）。AB = SC15〜16。' },
  { id: 'ox-075', category: '商品名からコーヒーを理解する', question: '比重選別は密度による豆の分離である。', answer: true, difficulty: 1, explanation: '比重選別は傾斜した振動テーブルで密度差により分離。重い豆は上方へ、軽い豆は下方へ。' },
  { id: 'ox-076', category: '商品名からコーヒーを理解する', question: '電子選別は色と形状を高速識別する。', answer: false, difficulty: 2, explanation: '電子選別はカメラ・レーザーセンサーで色を高速識別し、エアジェットで弾き飛ばす。形状ではなく色が主対象。' },
  { id: 'ox-077', category: '風味からコーヒーを理解する', question: 'ピーベリーはサイズが通常の豆より小さい。', answer: false, difficulty: 2, explanation: 'ピーベリーはサイズは通常の豆より小さいというわけではなく、形が丸いことで区別される。品質は優れるわけではない。' },
  { id: 'ox-078', category: '商品名からコーヒーを理解する', question: 'スペシャルティコーヒー基準ではカテゴリー1欠点は0個が条件である。', answer: true, difficulty: 2, explanation: 'SCAスペシャルティグレードはカテゴリー1欠点（重大欠点）0個、カテゴリー2欠点5個以内。' },
  { id: 'ox-079', category: '商品名からコーヒーを理解する', question: 'エチオピアはスクリーンサイズ方式で格付けしている。', answer: false, difficulty: 2, explanation: 'エチオピアは欠点数方式（G1〜G5）で格付け。スクリーンサイズ方式はコロンビア・ケニア。' },
  { id: 'ox-080', category: '商品名からコーヒーを理解する', question: 'ハンドピックは最終工程として行われ、最も精度が高い選別方法である。', answer: true, difficulty: 1, explanation: 'ハンドピック（手選別）は最終工程として行われ、人の目で最後のチェックを行う最も精度が高い方法。' },

  // 生豆の成分 (15 questions) - 8T, 7F
  { id: 'ox-081', category: '生豆', question: 'カフェインは焙煎で大幅に減少する。', answer: false, difficulty: 2, explanation: 'カフェインはほとんど変化しない。減少するのはショ糖・クロロゲン酸・アミノ酸。' },
  { id: 'ox-082', category: '焙煎', question: 'ショ糖は焙煎でカラメル化・メイラード反応の原料として消費される。', answer: true, difficulty: 2, explanation: 'ショ糖（少糖類）は焙煎で大幅に減少。カラメル化・メイラード反応に使用される。' },
  { id: 'ox-083', category: '生豆', question: 'クロロゲン酸は6〜9%含有され、焙煎で一部分解される。', answer: true, difficulty: 2, explanation: 'クロロゲン酸はアラビカ種5〜8%、カネフォラ種7〜10%。焙煎で一部分解。' },
  { id: 'ox-084', category: '焙煎', question: 'トリゴネリンはニコチン酸（ビタミンB3）に分解される。', answer: true, difficulty: 2, explanation: 'トリゴネリンは焙煎でニコチン酸（ナイアシン＝ビタミンB3）に分解。' },
  { id: 'ox-085', category: '生豆', question: 'アラビカ種の脂質含有量はカネフォラ種より高い。', answer: true, difficulty: 2, explanation: 'アラビカ種12〜18%、カネフォラ種9〜13%。アラビカ種の方が脂質が多い。' },
  { id: 'ox-086', category: '焙煎', question: '多糖類は焙煎による変化が比較的大きい。', answer: false, difficulty: 2, explanation: '多糖類（セルロース・ヘミセルロース）は焙煎による変化が比較的小さい。' },
  { id: 'ox-087', category: '焙煎', question: 'メイラード反応はアミノ酸＋少糖類で約150℃以上で開始される。', answer: true, difficulty: 2, explanation: 'メイラード反応は褐色色素と香気成分を生成し、約150℃以上で開始。' },
  { id: 'ox-088', category: '焙煎', question: '有機酸はコーヒーの酸味の基であり、焙煎で全て分解される。', answer: false, difficulty: 2, explanation: '有機酸は焙煎で一部分解、一部は生成される。全て分解されるわけではない。' },
  { id: 'ox-089', category: 'コーヒーをおいしく淹れるために', question: 'コーヒーオイル（脂質）はペーパーフィルターで除去されない。', answer: false, difficulty: 2, explanation: 'コーヒーオイルはペーパーフィルターで除去される。金属フィルターより味への影響が減少。' },
  { id: 'ox-090', category: '焙煎', question: '焙煎で生成される香気成分は約800〜1000種類以上である。', answer: true, difficulty: 2, explanation: '現在の分析では焙煎で800〜1000種類以上の香気成分が生成される。' },
  { id: 'ox-091', category: '焙煎', question: 'アミノ酸は焙煎で増加する。', answer: false, difficulty: 2, explanation: 'アミノ酸はメイラード反応に使用されるため焙煎で減少。増加しない。' },
  { id: 'ox-092', category: '生豆', question: 'アラビカ種のトリゴネリン含有量はカネフォラ種より高い。', answer: true, difficulty: 2, explanation: 'アラビカ種0.6〜1.3%、カネフォラ種0.3〜0.9%。アラビカ種の方が高い。' },
  { id: 'ox-093', category: '焙煎', question: '水分は焙煎で約5〜10%減少する。', answer: false, difficulty: 2, explanation: '水分は焙煎で約15〜20%減少（大幅に減少）。5〜10%ではなく15〜20%。' },
  { id: 'ox-094', category: '焙煎', question: 'アラビカ種の少糖類含有量は6〜9%である。', answer: true, difficulty: 1, explanation: 'アラビカ種の少糖類は6〜9%、カネフォラ種は3〜7%。焙煎でメイラード反応の原料になる。' },
  { id: 'ox-095', category: 'コーヒーをおいしく淹れるために', question: 'ペーパーフィルターはカフェストールも除去する。', answer: true, difficulty: 2, explanation: 'ペーパーフィルターはコーヒーオイル・微粉・カフェストールを除去。金属フィルターは通す。' },

  // 焙煎 (20 questions) - 10T, 10F
  { id: 'ox-096', category: '焙煎', question: '直火式焙煎機はシリンダーの真下に熱源があり穴あきシリンダーを使う。', answer: true, difficulty: 2, explanation: '直火式は熱源がシリンダー真下で穴あきシリンダー。輻射熱が豆に直接当たる。' },
  { id: 'ox-097', category: '焙煎', question: '熱風式焙煎機は熱源がシリンダーの真下にある。', answer: false, difficulty: 2, explanation: '熱風式は熱源が離れた位置にあり、加熱した空気をシリンダーに引き込む方式。' },
  { id: 'ox-098', category: '焙煎', question: '1ハゼは約180〜200℃で発生し豆が膨らみ始める。', answer: true, difficulty: 2, explanation: '1ハゼ（ファーストクラック）は約180〜200℃で「パチパチ」という音が鳴り豆が膨張。' },
  { id: 'ox-099', category: '焙煎', question: '2ハゼは約150〜170℃で油脂が表面に出てくる。', answer: false, difficulty: 2, explanation: '2ハゼ（セカンドクラック）は約220〜230℃で「チチチ」という音が鳴り油脂が表面に出る。' },
  { id: 'ox-100', category: '焙煎', question: '焙煎により豆の体積は約1.5〜2倍に膨張する。', answer: true, difficulty: 2, explanation: '焙煎により内部のCO₂・水蒸気で体積は約1.5〜2倍に膨張。' },
  { id: 'ox-101', category: '焙煎', question: '焙煎により豆の重量は約30%減少する。', answer: false, difficulty: 2, explanation: '焙煎により豆の重量は約15〜20%減少（水分蒸発）。30%ではなく15〜20%。' },
  { id: 'ox-102', category: '焙煎', question: 'ハイローストは最もスタンダードな焙煎度である。', answer: true, difficulty: 1, explanation: '焙煎度8段階：①ライト②シナモン③ミディアム④ハイ⑤シティ⑥フルシティ⑦フレンチ⑧イタリアン。ハイが④でスタンダード。' },
  { id: 'ox-103', category: '焙煎', question: 'ベイクドは長時間低温で焙煎しすぎた欠陥である。', answer: true, difficulty: 2, explanation: 'ベイクドは長時間低温焙煎による欠陥で、平坦な風味・甘みの欠如が特徴。' },
  { id: 'ox-104', category: '焙煎', question: 'スコーチは豆内部の未発達が原因である。', answer: false, difficulty: 2, explanation: 'スコーチは豆の表面だけが高温になる欠陥で、焦げ臭・苦味過多が生じる。未発達ではなく表面過熱が原因。' },
  { id: 'ox-105', category: '焙煎', question: 'ティッピングは豆の先端が焦げる欠陥である。', answer: true, difficulty: 2, explanation: 'ティッピングは豆の先端が焦げる欠陥で、焦げ味が混入。' },
  { id: 'ox-106', category: '焙煎', question: 'シナモンローストは薄茶色で高酸味が特徴である。', answer: true, difficulty: 1, explanation: 'シナモンは焙煎度2で薄茶色、高酸味が特徴の浅煎り。' },
  { id: 'ox-107', category: '焙煎', question: 'フレンチローストはイタリアンより浅い焙煎である。', answer: true, difficulty: 1, explanation: '焙煎度順：⑦フレンチ＜⑧イタリアン。フレンチの方がイタリアンより浅い。' },
  { id: 'ox-108', category: '焙煎', question: '輻射熱は電磁波を介して熱移動が発生する。', answer: true, difficulty: 2, explanation: '輻射（放射）は空間を介して隔てられた2つの物体表面間で電磁波による熱移動。' },
  { id: 'ox-109', category: '焙煎', question: '対流は流体の移動による熱移動である。', answer: true, difficulty: 2, explanation: '対流は流体（気体・液体）の移動による熱移動。焙煎では熱風による表面加熱。' },
  { id: 'ox-110', category: '焙煎', question: '伝導は豆の内部および豆同士の接触による熱移動である。', answer: true, difficulty: 2, explanation: '伝導は固体内の熱移動。焙煎では豆内部・豆同士・ドラムとの接触での熱移動。' },
  { id: 'ox-111', category: '焙煎', question: 'シティローストは中深煎りでバランスが良い。', answer: true, difficulty: 1, explanation: 'シティは焙煎度5で中深煎り、バランスが良い焙煎度。' },
  { id: 'ox-112', category: '焙煎', question: 'フルシティは2ハゼ後半の深煎りである。', answer: true, difficulty: 2, explanation: 'フルシティは焙煎度6で深煎り、2ハゼ後半の焙煎度。' },
  { id: 'ox-113', category: '焙煎', question: 'ミディアムローストは中煎りでスタンダードである。', answer: false, difficulty: 1, explanation: 'ミディアムは焙煎度3で浅煎り。スタンダードはハイ（焙煎度4）。' },
  { id: 'ox-114', category: '焙煎', question: '焙煎中に大量の二酸化炭素が生成される。', answer: true, difficulty: 2, explanation: '焙煎により豆内の二酸化炭素が大量に生成される。焙煎後のデガッシングで徐々に放出。' },
  { id: 'ox-115', category: '焙煎', question: 'イタリアンローストは最深煎りで炭化に近い。', answer: true, difficulty: 1, explanation: 'イタリアンは焙煎度8で最深煎り、炭化に近い焙煎度。' },

  // 粉砕・包装・保管 (10 questions) - 5T, 5F
  { id: 'ox-116', category: '粉砕', question: 'カッティング式（臼刃式）グラインダーは粒度が均一になりやすい。', answer: true, difficulty: 2, explanation: 'カッティング式は2枚の刃で豆を切削し粒度が均一。フラット刃とコニカル刃がある。' },
  { id: 'ox-117', category: '粉砕', question: 'ブレード式グラインダーは粒度が均一である。', answer: false, difficulty: 1, explanation: 'ブレード式（プロペラ式）は粒度が不均一。カッティング式が均一。' },
  { id: 'ox-118', category: '粉砕', question: '粉砕後のコーヒーは酸化・劣化が急速に進む。', answer: true, difficulty: 2, explanation: '粉砕により表面積が増大し、酸化・劣化が急速に進む。CO₂の放出も加速。' },
  { id: 'ox-119', category: '包装', question: 'バルブ付き包装はCO₂を排出するワンウェイバルブである。', answer: true, difficulty: 2, explanation: 'バルブ付き包装はCO₂を外に逃がし、酸素を遮断するワンウェイバルブ付き。' },
  { id: 'ox-120', category: '包装', question: '真空包装は焙煎直後から使用できる。', answer: false, difficulty: 2, explanation: '真空包装はCO₂が落ち着いてから使用。焙煎直後はバルブ付き包装を使用。' },
  { id: 'ox-121', category: 'コーヒーのおいしさを保つために', question: 'コーヒーの劣化原因は酸素・水分・高温・光である。', answer: true, difficulty: 1, explanation: 'コーヒー劣化の4大敵：①酸素（酸化）②水分（湿気）③高温④光（紫外線）' },
  { id: 'ox-122', category: '生豆', question: '生豆の適正水分含有率は15〜20%である。', answer: false, difficulty: 2, explanation: '生豆の適正水分含有率は10〜12%以下（脱殻後の目安）。15〜20%ではなく10〜12%。' },
  { id: 'ox-123', category: '包装', question: 'ガス置換包装は窒素で酸化防止効果を高める。', answer: true, difficulty: 2, explanation: 'ガス置換包装（窒素充填）は袋内の空気を窒素で置換し酸化防止効果を高める。' },
  { id: 'ox-124', category: '焙煎', question: 'デガッシングはCO₂が放出される過程である。', answer: true, difficulty: 2, explanation: 'デガッシング（脱気）は焙煎直後から数日〜数週間かけてCO₂が徐々に放出される。' },
  { id: 'ox-125', category: '包装', question: '1コンテナ（20フィート）のコーヒー搭載量は通常1〜3トンである。', answer: false, difficulty: 2, explanation: '1コンテナ搭載量は通常15〜18トン程度（60kg袋）。1〜3トンではなく15〜18トン。' },

  // 産地・格付け・流通 (15 questions) - 8T, 7F
  { id: 'ox-126', category: '商品名からコーヒーを理解する', question: 'ブラジルは世界最大のコーヒー生産国で世界シェア約35〜38%である。', answer: true, difficulty: 1, explanation: 'ブラジルは生産量1位でシェア約35〜38%。2位ベトナム（15〜17%）、3位コロンビア（7〜8%）。' },
  { id: 'ox-127', category: '商品名からコーヒーを理解する', question: 'コロンビアの格付けは欠点数方式である。', answer: false, difficulty: 1, explanation: 'コロンビアはスクリーンサイズ方式（Supremo/Excelso）。ブラジルが欠点数方式。' },
  { id: 'ox-128', category: '商品名からコーヒーを理解する', question: 'グアテマラはSHB（標高1,350m以上）でスクリーンサイズ方式である。', answer: false, difficulty: 2, explanation: 'グアテマラはSHB標高1,350m以上で標高方式を採用。スクリーンサイズ方式ではない。' },
  { id: 'ox-129', category: '商品名からコーヒーを理解する', question: 'ケニアはスクリーンサイズとカップテストの複合方式で格付けしている。', answer: true, difficulty: 2, explanation: 'ケニアはAA（SC17〜18）等スクリーン＋カップテストの複合方式。' },
  { id: 'ox-130', category: '商品名からコーヒーを理解する', question: 'エチオピアの格付けはG1（0〜3個欠点）からG5（46〜90個欠点）である。', answer: true, difficulty: 2, explanation: 'エチオピアは欠点数方式で300gサンプルでG1〜G5に分類。' },
  { id: 'ox-131', category: '風味からコーヒーを理解する', question: 'ブルーマウンテンはジャマイカのブルーマウンテン地区産アラビカ種である。', answer: true, difficulty: 1, explanation: 'ブルーマウンテンはジャマイカ・ブルーマウンテン地区産アラビカ種。日本が最大輸入国。' },
  { id: 'ox-132', category: '風味からコーヒーを理解する', question: 'コスタリカはロブスタ種の栽培を法律で禁止している。', answer: true, difficulty: 2, explanation: 'コスタリカは法律によりロブスタ種の栽培を禁止。アラビカ種のみ。' },
  { id: 'ox-133', category: '商品名からコーヒーを理解する', question: 'ハワイはアメリカ唯一の商業的コーヒー産地である。', answer: true, difficulty: 2, explanation: 'ハワイ島コナ地区はアメリカ合衆国唯一の商業的コーヒー産地。' },
  { id: 'ox-134', category: '商品名からコーヒーを理解する', question: 'インドの「モンスーニング」はモンスーンの乾いた風にさらして熟成させる。', answer: false, difficulty: 2, explanation: 'モンスーニングはモンスーンの湿った風にさらして熟成。乾いた風ではなく湿った風。' },
  { id: 'ox-135', category: '商品名からコーヒーを理解する', question: 'モカはイエメンのモカ港に由来する名称である。', answer: true, difficulty: 1, explanation: 'モカはイエメンのモカ港に由来。イエメン産またはエチオピア産。' },
  { id: 'ox-136', category: '商品名からコーヒーを理解する', question: 'ICOは1963年に設立された国際コーヒー機関である。', answer: true, difficulty: 2, explanation: 'ICO（International Coffee Organization）は1963年にロンドンで設立。' },
  { id: 'ox-137', category: '商品名からコーヒーを理解する', question: 'ベトナムはカネフォラ種（ロブスタ）が約95%である。', answer: true, difficulty: 2, explanation: 'ベトナムはカネフォラ種が約95%で、世界2位の生産国。主にインスタント・ブレンド用。' },
  { id: 'ox-138', category: '商品名からコーヒーを理解する', question: 'タンザニアのキリマンジャロは標高方式で格付けされている。', answer: false, difficulty: 2, explanation: 'タンザニアはスクリーンサイズ＋カップテスト方式。標高方式はグアテマラ等。' },
  { id: 'ox-139', category: '風味からコーヒーを理解する', question: 'マンデリンはインドネシア・スマトラ島北部産のアラビカ種である。', answer: true, difficulty: 1, explanation: 'マンデリンはインドネシア・スマトラ島北部産。スマトラ式精選で深緑色が特徴。' },
  { id: 'ox-140', category: '風味からコーヒーを理解する', question: 'コロンビアは年2回の収穫期を持つ。', answer: true, difficulty: 2, explanation: 'コロンビアはメインクロップ（10〜2月）とミタカ（3〜6月）の年2回収穫。' },

  // 抽出・品質管理 (10 questions) - 5T, 5F
  { id: 'ox-141', category: 'カップテストの手順', question: 'SCA方式のカッピングは粉8.25gに湯150mlを使用する。', answer: true, difficulty: 2, explanation: 'SCA方式：粉8.25g（±0.25g）、湯150ml、湯温93℃±1℃、4分間浸漬。' },
  { id: 'ox-142', category: 'コーヒーをおいしく淹れるために', question: '抽出率の適正範囲は18〜22%である。', answer: true, difficulty: 2, explanation: '適正抽出率は18〜22%。18%未満は未抽出、22%超過は過抽出。' },
  { id: 'ox-143', category: 'コーヒーをおいしく淹れるために', question: 'ドリップコーヒーのTDS目安は1.15〜1.35%である。', answer: true, difficulty: 2, explanation: 'TDS（Total Dissolved Solids）ドリップ目安：1.15〜1.35%（11.5〜13.5g/L）。' },
  { id: 'ox-144', category: 'コーヒーをおいしく淹れるために', question: 'ペーパーフィルターはコーヒーオイルを除去する。', answer: true, difficulty: 1, explanation: 'ペーパーフィルターはコーヒーオイル・微粉・カフェストールを除去。金属フィルターは通す。' },
  { id: 'ox-145', category: 'コーヒーをおいしく淹れるために', question: 'ドリップのコーヒーと水の比率は粉1に対して水15〜18である。', answer: true, difficulty: 2, explanation: 'ドリップのブリューレシオ：粉1に対して水15〜18（例：粉15gに湯250ml）。' },
  { id: 'ox-146', category: '生豆', question: '黒豆の欠点は発酵臭・腐敗臭を生む。', answer: true, difficulty: 1, explanation: '黒豆（デッドビーン）は過熟・腐敗・過度の発酵で、発酵臭・腐敗臭が生じる。' },
  { id: 'ox-147', category: 'コーヒーをおいしく淹れるために', question: '未熟豆は甘い風味を生む。', answer: false, difficulty: 1, explanation: '未熟豆は糖分が少ないため渋み・青臭さ・不快な酸味を生む。甘くない。' },
  { id: 'ox-148', category: 'カップテストの手順', question: 'SCAのカッピング評価項目は11項目である。', answer: true, difficulty: 2, explanation: 'SCAカッピングは採点項目7+存在確認項目3+減点項目1=計11項目。' },
  { id: 'ox-149', category: 'コーヒーをおいしく淹れるために', question: '理想的な湯硬度は150〜300ppm程度の軟水〜中硬水である。', answer: true, difficulty: 2, explanation: '抽出に影響する湯硬度（ミネラル分）の理想値は150〜300ppm程度の軟水〜中硬水。' },
  { id: 'ox-150', category: '商品名からコーヒーを理解する', question: 'SCAブレイキングはクラスト（表面の粉の層）を5回かき分ける。', answer: false, difficulty: 2, explanation: 'SCAブレイキングはクラストを3回かき分ける。5回ではなく3回が正しい。' },

  // Advanced Difficulty 3 Questions (ox-151 to ox-170)
  // 焙煎 (5 questions)
  { id: 'ox-151', category: '焙煎', question: '焙煎により豆の体積は約1.5〜2倍に膨張する。', answer: true, difficulty: 3, explanation: '焙煎により内部のCO₂・水蒸気で豆の体積は約1.5〜2倍に膨張する。これが焙煎による物理的変化の一つ。' },
  { id: 'ox-152', category: '焙煎', question: '直火式焙煎機は輻射熱が豆に直接当たる方式である。', answer: true, difficulty: 3, explanation: '直火式は熱源がシリンダーの真下にあり、穴あきシリンダーを使用するため輻射熱が豆に直接当たる。' },
  { id: 'ox-153', category: '焙煎', question: '焙煎により豆の重量は約25〜30%減少する。', answer: false, difficulty: 3, explanation: '焙煎により豆の重量は約15〜20%減少する。25〜30%は多すぎる。数字の微細な違いが出題される。' },
  { id: 'ox-154', category: '焙煎', question: '焙煎中に生成される香気成分は約500〜700種類である。', answer: false, difficulty: 3, explanation: '焙煎で生成される香気成分は約800〜1000種類以上。500〜700では少なすぎる。' },
  { id: 'ox-155', category: '焙煎', question: '2ハゼは約190〜210℃で発生する。', answer: false, difficulty: 3, explanation: '2ハゼは約220〜230℃で発生する。190〜210℃は低すぎる。わずかな数字の違いが試験に出題される。' },

  // 産地・格付け・流通 (5 questions)
  { id: 'ox-156', category: '商品名からコーヒーを理解する', question: 'ブラジルはスクリーンサイズと欠点数方式の複合方式で格付けしている。', answer: true, difficulty: 3, explanation: 'ブラジルの格付けはNo.2（最高）〜No.8と欠点数方式、またスクリーン17/18以上がFineという複合方式。' },
  { id: 'ox-157', category: '生豆', question: 'グアテマラの標高方式ではSHBが1,200m以上の栽培地を示す。', answer: false, difficulty: 3, explanation: 'グアテマラのSHB（Strictly Hard Bean）は標高1,350m以上。1,200mではなく1,350m以上が正確。' },
  { id: 'ox-158', category: '商品名からコーヒーを理解する', question: 'タンザニアのキリマンジャロは標高方式のみで格付けされている。', answer: false, difficulty: 3, explanation: 'タンザニアはスクリーンサイズ＋カップテストの複合方式で格付け。標高方式ではない。' },
  { id: 'ox-159', category: '商品名からコーヒーを理解する', question: 'インドのモンスーンマラバールはモンスーニング処理により独特のまろやかさと低酸味が特徴である。', answer: true, difficulty: 3, explanation: 'モンスーニングはモンスーンの湿った風にさらして熟成。モンスーンマラバールはインド産コーヒーの代表的ブランド。' },
  { id: 'ox-160', category: '商品名からコーヒーを理解する', question: 'ベトナムはアラビカ種が約95%を占める主要産地である。', answer: false, difficulty: 3, explanation: 'ベトナムはカネフォラ種（ロブスタ）が約95%。アラビカではなくカネフォラが主流。' },

  // 抽出・品質管理 (5 questions)
  { id: 'ox-161', category: 'カップテストの手順', question: 'SCA方式のカッピングは4分間浸漬した後にクラストを3回かき分ける。', answer: true, difficulty: 3, explanation: 'SCA方式は粉8.25gに湯150mlで4分間浸漬後、クラスト（表面の粉層）を3回かき分ける。5回ではなく3回が正確。' },
  { id: 'ox-162', category: 'コーヒーをおいしく淹れるために', question: '抽出率が18%未満の場合は未抽出で酸味が際立つ傾向がある。', answer: true, difficulty: 3, explanation: '適正抽出率は18〜22%。18%未満は未抽出で酸味が際立つ・薄い・未発達な風味が特徴。22%超過は過抽出で苦味が強い。' },
  { id: 'ox-163', category: 'コーヒーをおいしく淹れるために', question: 'ドリップコーヒーのTDS目安は1.20〜1.40%である。', answer: false, difficulty: 3, explanation: 'TDS目安は1.15〜1.35%（11.5〜13.5g/L）。1.20〜1.40%は範囲がズレている。' },
  { id: 'ox-164', category: 'コーヒーをおいしく淹れるために', question: 'ドリップのコーヒーと水の比率は粉1に対して水16〜19が理想的である。', answer: false, difficulty: 3, explanation: 'ドリップのブリューレシオは粉1に対して水15〜18。16〜19では上限が高すぎる。' },
  { id: 'ox-165', category: '商品名からコーヒーを理解する', question: 'スペシャルティコーヒーはカテゴリー1欠点が1個まで許容される。', answer: false, difficulty: 3, explanation: 'スペシャルティグレードはカテゴリー1欠点は0個が条件。1個でも許容されない。' },

  // 精選方法 (3 questions)
  { id: 'ox-166', category: '風味からコーヒーを理解する', question: 'パルプドナチュラルはブラジルが開発地で、果肉を除去した後ミューシレージを残したまま乾燥する。', answer: true, difficulty: 3, explanation: 'パルプドナチュラルはブラジルが開発地。パルパーで果肉は除去するがミューシレージは残して乾燥。ハニープロセスとも呼ばれる。' },
  { id: 'ox-167', category: '風味からコーヒーを理解する', question: 'スマトラ式は完全に乾燥した状態で脱殻される。', answer: false, difficulty: 3, explanation: 'スマトラ式の最大の特徴は半生きの状態（水分30〜35%）で脱殻すること。完全乾燥ではなく半乾き状態が特徴。' },
  { id: 'ox-168', category: '風味からコーヒーを理解する', question: 'ナチュラル精選は乾燥前に未成熟果実を機械で効率的に除去できる。', answer: false, difficulty: 3, explanation: 'ナチュラル精選は未成熟果実を乾燥前に取り除けない。パルプドナチュラルやウォッシュドで機械除去可能。' },

  // 生豆の成分 (2 questions)
  { id: 'ox-169', category: '焙煎', question: '水分は焙煎で約15〜20%減少する。', answer: true, difficulty: 3, explanation: '水分は焙煎で約15〜20%減少する。これは大幅な減少。12〜15%では少なすぎる。' },
  { id: 'ox-170', category: '焙煎', question: 'ショ糖は焙煎中にカラメル化・メイラード反応の原料として大幅に減少する。', answer: true, difficulty: 3, explanation: 'ショ糖（少糖類）は焙煎で大幅に減少し、カラメル化とメイラード反応によりコーヒー色と香りが生成される。' },

  // 追加問題 (ox-171 to ox-177) - ナレッジ追加分カバー
  { id: 'ox-171', category: '生豆', question: '不完全果実の判別方法として、水に浮かべて沈んだものが不完全果実である。', answer: false, difficulty: 1, explanation: '不完全果実は種子の形成が不十分で内部に空洞があるため、水に浮かべると浮く。沈むのは正常な果実。' },
  { id: 'ox-172', category: '風味からコーヒーを理解する', question: '通常1つの果実に2つ入っている平らな面を持つ豆をフラットビーンと呼び、全体の約90%を占める。', answer: true, difficulty: 1, explanation: 'フラットビーンは通常の豆で全体の約90%。残りの5〜20%がピーベリー（1粒だけの丸い豆）。' },
  { id: 'ox-173', category: '焙煎', question: '炭焼きコーヒーとは、熱源の50%以上を炭としたコーヒーのことである。', answer: false, difficulty: 1, explanation: '炭焼きコーヒーは熱源の100%を炭としなければならない。50%では不十分。' },
  { id: 'ox-174', category: '風味からコーヒーを理解する', question: 'プレミックスとは焙煎豆の状態でブレンドする方法であり、味の自由度が高い。', answer: false, difficulty: 2, explanation: 'プレミックスは生豆の状態でブレンドしてから焙煎する方法で、工程はシンプルだが味の自由度は低い。焙煎豆でブレンドするのはアフターミックス。' },
  { id: 'ox-175', category: '焙煎', question: 'アフターミックスは工程が複雑だが、それぞれの豆を最適な焙煎度で仕上げられるため味の自由度がほぼ無限である。', answer: true, difficulty: 2, explanation: 'アフターミックスは焙煎豆の状態でブレンドする方法。各豆を個別に最適な焙煎ができるため味の自由度が高いが、焙煎豆を保管するサイロやミキサーなどの設備が必要。' },
  { id: 'ox-176', category: 'コーヒーをおいしく淹れるために', question: '抽出液の風味に影響を与える要素は、化学的な成分変化と蒸発による温度変化の2つである。', answer: true, difficulty: 1, explanation: '抽出後のコーヒー液の風味は①化学的な成分変化（酸化など）と②蒸発による温度変化の2つの要素によって変化する。' },
  { id: 'ox-177', category: 'コーヒーのおいしさを保つために', question: '抽出液を保存する場合、高温の方が化学的な成分変化が起きにくいため望ましい。', answer: false, difficulty: 1, explanation: '抽出液の保存は低温が望ましい。化学的な成分変化は高温で起きやすいため、低温保存が風味劣化を抑える。' },

  // 追加問題 (ox-178 to ox-197) - CSV未カバー分
  { id: 'ox-178', category: '風味からコーヒーを理解する', question: '非水洗式（ナチュラル）の最終乾燥状態は果実のままである。', answer: true, difficulty: 1, explanation: '非水洗式は果実ごと乾燥させるため、最終乾燥状態は果実。水洗式はパーチメントコーヒー、スマトラ式は生豆が最終状態。' },
  { id: 'ox-179', category: '風味からコーヒーを理解する', question: '水洗式（ウォッシュド）の最終乾燥状態は生豆である。', answer: false, difficulty: 1, explanation: '水洗式の最終乾燥状態はパーチメントコーヒー。生豆が最終乾燥状態なのはスマトラ式。' },
  { id: 'ox-180', category: '生豆', question: 'アラビカ種が発見されたのは19世紀ごろ、エチオピアにおいてである。', answer: false, difficulty: 1, explanation: 'アラビカ種は18世紀ごろエチオピアで発見された。19世紀ごろビクトリア湖近くで発見されたのはカネフォラ種。' },
  { id: 'ox-181', category: 'コーヒーの周辺知識', question: 'ブレンドコーヒーで特定産地を強調した商品名にする場合、その豆を生豆換算で50%以上配合しなければならない。', answer: false, difficulty: 2, explanation: '特定産地を強調する場合は生豆換算で30%以上の配合が必要。50%ではなく30%が正しい。' },
  { id: 'ox-182', category: '焙煎', question: '焙煎が進むと苦味は増加し、酸味は減少する。', answer: true, difficulty: 1, explanation: '焙煎が進むにつれて苦味は増加し、酸味は減少する。浅煎りは酸味が強く、深煎りは苦味が強い。' },
  { id: 'ox-183', category: '焙煎', question: '焙煎豆に含まれる水分は約10%である。', answer: false, difficulty: 1, explanation: '焙煎豆の水分は3%以下。熱により蒸発し失われる。生豆の水分が10〜13%。' },
  { id: 'ox-184', category: '焙煎', question: '生豆に含まれるクロロゲン酸は5〜10%であり、焙煎度に応じて減少する。', answer: true, difficulty: 2, explanation: 'クロロゲン酸は生豆に5〜10%含まれ、焙煎豆では5%以下に減少する。焙煎度が深いほど減少幅が大きい。' },
  { id: 'ox-185', category: 'コーヒーをおいしく淹れるために', question: 'アルカリ性の水を使用してコーヒーを抽出すると、酸味が強調される。', answer: false, difficulty: 2, explanation: 'アルカリ性の水はコーヒーの酸味を中和する。酸味が強調されるのではなく、中和されて穏やかになる。' },
  { id: 'ox-186', category: 'コーヒーをおいしく淹れるために', question: '抽出時において、酸味成分の移動は速く、お湯の温度・時間・挽き方の影響をあまり受けない。', answer: true, difficulty: 2, explanation: '酸味成分は移動が速いため、抽出条件の影響を受けにくい。苦味成分は速いものから遅いものまで様々で、遅いものほど条件の影響を受けやすい。' },
  { id: 'ox-187', category: 'コーヒーをおいしく淹れるために', question: 'コーヒー抽出で最も遅く風味に影響するのは、粉表面からお湯への移動である。', answer: false, difficulty: 2, explanation: '最も遅く影響するのは「粉内部から粉表面への移動」。粉表面からお湯への移動や、お湯のろ過はそれより速い。' },
  { id: 'ox-188', category: 'コーヒーをおいしく淹れるために', question: 'モカポットの圧力は約9気圧である。', answer: false, difficulty: 1, explanation: 'モカポットの圧力は1.5気圧程度。9気圧はエスプレッソマシンの圧力。' },
  { id: 'ox-189', category: 'コーヒーをおいしく淹れるために', question: '水出しコーヒーに使用する粉は粗挽きが適している。', answer: false, difficulty: 2, explanation: '水出しコーヒーは細かい粉を使う。抽出温度の低さによる抽出効率の低さを、時間と粉の細かさでカバーする。' },
  { id: 'ox-190', category: '焙煎', question: 'アイスコーヒーは一般的に浅煎りの豆を使い薄く淹れる。', answer: false, difficulty: 1, explanation: 'アイスコーヒーは深煎りを使い濃く淹れるのが一般的。冷たいと味を感じにくいことと、ガムシロップやミルクとの相性に起因する。' },
  { id: 'ox-191', category: 'コーヒーのおいしさを保つために', question: '温度がコーヒーに与える影響は、水分・酸素の影響に比べて大きい。', answer: false, difficulty: 2, explanation: '温度の影響は水分・酸素の影響に比べて小さい。最も大きい影響は酸素（0%→1%で約10倍）である。' },
  { id: 'ox-192', category: 'コーヒーのおいしさを保つために', question: '経時変化を遅くするにはガスバリア性の高い包装が好ましい。', answer: true, difficulty: 1, explanation: 'ガスバリア性の高い包装は酸素や水分の透過を防ぎ、経時変化を遅くする。ただしコストが高い。' },
  { id: 'ox-193', category: 'コーヒーのおいしさを保つために', question: 'コーヒーの経時変化は、適切な保管方法により完全に避けることができる。', answer: false, difficulty: 1, explanation: 'コーヒーの経時変化は変化を遅くすることはできるが、完全に避けることはできない。' },
  { id: 'ox-194', category: 'コーヒーの周辺知識', question: 'フードファディズムとは、食べ物が健康に与える影響を科学的に正しく評価することである。', answer: false, difficulty: 1, explanation: 'フードファディズムとは、食べ物が健康や病気に与える影響を「過大に」評価すること、あるいは信じ込むこと。科学的に正しい評価ではない。' },
  { id: 'ox-195', category: 'コーヒーの周辺知識', question: 'インスタントコーヒーの製法のうち、フリーズドライはスプレードライより粒度が細かい。', answer: false, difficulty: 2, explanation: '粒度が細かいのはスプレードライ。フリーズドライは粒が大きく不規則な形状。フリーズドライの方が風味が良いとされる。' },
  { id: 'ox-196', category: 'コーヒーの周辺知識', question: 'PETボトル入りコーヒーの殺菌方法はレトルト殺菌（加圧加熱殺菌）である。', answer: false, difficulty: 2, explanation: 'PETボトル入りコーヒーは高温短時間殺菌。レトルト殺菌（加圧加熱殺菌）は缶コーヒーの殺菌方法。' },
  { id: 'ox-197', category: 'コーヒーの周辺知識', question: 'リキッドコーヒーのうち、乳固形分が3%以上のものはコーヒー含有量に関わらず「乳飲料」に分類される。', answer: true, difficulty: 2, explanation: '乳固形分が3%以上のリキッドコーヒーは、コーヒーの生豆換算量に関わらず「乳飲料」と表示する。' },

  // 追加問題 (ox-198 to ox-203) - CSV最終カバー分
  { id: 'ox-198', category: '商品名からコーヒーを理解する', question: '比色選別とは、振動を与えて重い豆と軽い豆を分ける選別方法である。', answer: false, difficulty: 1, explanation: '振動で重い豆と軽い豆を分けるのは比重選別。比色選別は目視または光の反射率の違いを利用して、外観に異常のある豆や色の異なる豆を分ける方法。' },
  { id: 'ox-199', category: 'コーヒーをおいしく淹れるために', question: 'エスプレッソの液体表面を覆う泡「クレマ」は、コーヒーオイルやタンパク質と空気が乳化したものである。', answer: true, difficulty: 1, explanation: 'クレマはコーヒーオイルやタンパク質、空気が乳化してできた泡。エスプレッソ特有の見た目と食感を生む。' },
  { id: 'ox-200', category: 'コーヒーをおいしく淹れるために', question: 'アイスコーヒーと水出しコーヒーは同じ製法で作られる。', answer: false, difficulty: 1, explanation: 'アイスコーヒーはほとんどが熱湯抽出したものを急冷して作る。水出しコーヒーは水を使って抽出する。水出しコーヒーはアイスコーヒーの一部。' },
  { id: 'ox-201', category: 'コーヒーのおいしさを保つために', question: 'コーヒーの吸湿性は低い。', answer: false, difficulty: 1, explanation: 'コーヒーの吸湿性は高い。水分含量が1.5%増加すると劣化速度は約1.6倍になる。' },
  { id: 'ox-202', category: 'コーヒーのおいしさを保つために', question: 'コーヒーを1ヶ月間蛍光灯下で保存した場合、過酸化物価（POV）は暗所保存の約5倍になる。', answer: false, difficulty: 2, explanation: '蛍光灯下で1ヶ月保存した場合、POV（過酸化物価：油脂の酸化度を示す指標）は暗所保存の約2倍弱。5倍は過大。紫外線が主な原因。' },
  { id: 'ox-203', category: 'コーヒーのおいしさを保つために', question: '水分含量が1.5%増加するとコーヒーの劣化速度は約1.6倍になる。', answer: true, difficulty: 2, explanation: '水分はコーヒーの劣化に大きな影響を与える。1.5%の水分増加で劣化速度が約1.6倍に。コーヒーは吸湿性が高いため注意が必要。' },
  { id: 'ox-204', category: '粉砕', question: 'コニカルカッター（円錐刃）はフラットカッター（平刃）よりも粒度の均一性が高い。', answer: true, difficulty: 1, explanation: 'コニカルカッターは低速回転で発熱が少なく、豆が自然に奥に進むため粒度の均一性が非常に高い。フラットカッターは粗調整向きで均一性は中程度。' },
  { id: 'ox-205', category: '粉砕', question: 'ロールグラインダー式は家庭用の小型粉砕機として広く使われている。', answer: false, difficulty: 1, explanation: 'ロールグラインダー式は対向する2本のロールで粉砕する方式で、大量生産向けの業務用粉砕機である。家庭用ではない。' },
  { id: 'ox-206', category: '粉砕', question: 'コーヒー豆を粉砕すると表面積は約10〜100倍に増加する。', answer: true, difficulty: 2, explanation: '粉砕により豆から粉への変化で表面積は約10〜100倍に増大し、これにより酸化・劣化が飛躍的に加速する。' },
  { id: 'ox-207', category: '粉砕', question: 'エスプレッソには粗挽きの粉が適している。', answer: false, difficulty: 1, explanation: 'エスプレッソには極細挽き（パウダー状）の粉が適している。9気圧の高圧で25〜30秒の短時間抽出を行うため、細かい粉で十分な抽出を得る。' },
  { id: 'ox-208', category: '粉砕', question: 'フレンチプレスには粗挽きの粉が適している。', answer: true, difficulty: 1, explanation: 'フレンチプレスは浸漬法で4分程度の浸漬時間があるため、粗挽き（砂糖粒程度）の粉が適している。細挽きだと過抽出になる。' },
  { id: 'ox-209', category: '粉砕', question: '粒度が不均一な場合、過抽出と未抽出が同時に発生し、複雑で不快な風味になる。', answer: true, difficulty: 2, explanation: '粒度が不均一だと、粗い粒は抽出不足（酸味）、細かい粒は過抽出（苦味・雑味）となり、両方の問題が同時に発生する。' },
  { id: 'ox-210', category: '粉砕', question: 'ブレード式グラインダーは高速回転のため発熱が少なく、香り成分が保たれやすい。', answer: false, difficulty: 2, explanation: 'ブレード式は高速回転のため摩擦熱による発熱が多く、揮発成分（香気成分）が失われやすい。発熱が少ないのはコニカルカッター。' },
  { id: 'ox-211', category: '粉砕', question: '粉砕の最適なタイミングは抽出直前である。', answer: true, difficulty: 1, explanation: '抽出直前の粉砕（On-Demand Grinding）が最も好ましい。新鮮な香りと風味を最大限に保ち、抽出時に最高の状態で機能する。' },
  { id: 'ox-212', category: 'カップテストの手順', question: 'SCA方式のカッピングでは、クラストのブレイキングは浸漬後正確に4分経過した時点で行う。', answer: true, difficulty: 1, explanation: '4分間浸漬した後、スプーンで表面のクラスト（粉の層）を3回かき分ける。このタイミングでアロマも評価する。' },
  { id: 'ox-213', category: 'カップテストの手順', question: 'SCA方式のカッピング評価項目のうち、クリーンカップ・スウィートネス・ユニフォーミティは採点項目である。', answer: false, difficulty: 2, explanation: 'クリーンカップ・スウィートネス・ユニフォーミティは「存在確認項目」であり、5カップすべてで特性が確認されれば各10点。採点項目（6〜10点で採点）とは異なる。' },
  { id: 'ox-214', category: 'カップテストの手順', question: 'SCA方式のカッピングで、ディフェクトのTaint（軽度の欠陥）は4点の減点となる。', answer: false, difficulty: 2, explanation: 'Taint（軽度の欠陥）は−2点、Fault（重度の欠陥）は−4点の減点。' },
  { id: 'ox-215', category: 'カップテストの手順', question: 'SCA方式のカッピングで使用する湯の温度は93℃±1℃である。', answer: true, difficulty: 1, explanation: '93℃±1℃の厳密な温度管理が必須。85℃以下だと未抽出、100℃近いと過抽出になる。' },
  { id: 'ox-216', category: 'カップテストの手順', question: 'SCAJ方式では80点以上がスペシャルティコーヒーとして認定される。', answer: true, difficulty: 1, explanation: 'SCAJ方式もSCA方式と同様に80点以上がスペシャルティコーヒーの認定基準。ただし評価項目と配点が異なる。' },
  { id: 'ox-217', category: 'カップテストの手順', question: 'カッピング環境では香水や調理臭がある場所でも正確な評価が可能である。', answer: false, difficulty: 1, explanation: 'カッピングは無臭環境で行うことが必須。周囲の臭いがアロマ評価を妨害するため、香水・消臭剤・調理臭を避ける。' },
  { id: 'ox-218', category: 'カップテストの手順', question: 'ブラインドカッピングとは、豆の産地・価格・名前を伏せて評価することである。', answer: true, difficulty: 1, explanation: 'ブラインドカッピングは先入観を排除し、客観的な評価を行うための方法。競技会や品質検査で必須とされている。' },
  { id: 'ox-219', category: 'コーヒーのおいしさを保つために', question: '焙煎後の適飲期は焙煎後3〜14日である。', answer: true, difficulty: 1, explanation: '焙煎後3〜14日が最も風味が安定している。直後はCO₂が多く抽出困難、2週間以上経過すると酸化が進む。' },
  { id: 'ox-220', category: 'コーヒーのおいしさを保つために', question: '酸素濃度が0%から1%になると、コーヒーの劣化速度は約2倍になる。', answer: false, difficulty: 3, explanation: '酸素濃度が0%→1%になると劣化速度は約10倍に加速する。ただし5%以上では大差がない。酸素はコーヒーの最大の敵。' },
  { id: 'ox-221', category: 'コーヒーのおいしさを保つために', question: 'コーヒー豆は粉にすると表面積が数百倍に増加し、酸化が加速する。', answer: true, difficulty: 1, explanation: '粉砕により表面積が大幅に増加するため、豆のままなら週単位の酸化が、粉では日単位に加速する。' },
  { id: 'ox-222', category: 'コーヒーのおいしさを保つために', question: '冷蔵庫から取り出したコーヒー豆はすぐに蓋を開けて使用してよい。', answer: false, difficulty: 2, explanation: '冷蔵庫から取り出す際は温度差で結露が発生するため、密閉容器のまま常温に戻してから（約10分）蓋を開ける。' },
  { id: 'ox-223', category: 'コーヒーのおいしさを保つために', question: '抽出液を保存する場合、高温より低温の方が望ましい。', answer: true, difficulty: 1, explanation: '化学的な成分変化は高温で起きやすいため、抽出液の保存は低温が望ましい。' },
  { id: 'ox-224', category: 'コーヒーのおいしさを保つために', question: 'コーヒーの劣化4大敵のうち、最も影響が大きいのは温度である。', answer: false, difficulty: 2, explanation: '温度の影響は水分・酸素の影響に比べて小さい。最も大きい影響は酸素（0→1%で10倍）である。' },
  { id: 'ox-225', category: 'コーヒーのおいしさを保つために', question: 'デガッシングのピークは焙煎後3〜5日で、2週間程度で落ち着く。', answer: true, difficulty: 2, explanation: '焙煎直後からCO₂放出が開始、3〜5日がピーク、2週間程度で落ち着く。豆の重量の約5〜10%に相当するCO₂が放出される。' },
  { id: 'ox-226', category: 'コーヒーのおいしさを保つために', question: 'コーヒー豆の吸湿性は低く、湿度の影響をほとんど受けない。', answer: false, difficulty: 1, explanation: 'コーヒー豆の吸湿性は高い。水分含量が1.5%増加すると劣化速度は約1.6倍になる。' },
  { id: 'ox-227', category: '包装', question: 'ガス置換包装（窒素充填）は焙煎直後から使用できる。', answer: true, difficulty: 2, explanation: 'ガス置換包装はCO₂放出中でも使用可能。パッケージ内の酸素を窒素に置き換えるため、焙煎直後から使用できる。' },
  { id: 'ox-228', category: '包装', question: 'アルミ蒸着フィルムの酸素透過率は0.1 cc/m²·day未満で、最も優れたガスバリア性を持つ包材の一つである。', answer: true, difficulty: 2, explanation: 'アルミ蒸着フィルムは酸素透過率が0.1未満で、ガスバリア性・遮光性・水分バリア性に優れた高級包材。' },
  { id: 'ox-229', category: '包装', question: 'クラフト紙は通気性があるため、長期保存に適している。', answer: false, difficulty: 1, explanation: 'クラフト紙はガスバリア性がなく通気性があるため、短期保存向け。保存期間は数日〜1週間程度。' },
  { id: 'ox-230', category: '包装', question: '缶詰は遮光性・密閉性が最高レベルで、1年以上の保存が可能である。', answer: true, difficulty: 1, explanation: '缶詰（アルミ・スチール）は遮光性・密閉性が最高レベルで、酸素・光・水分すべてを遮断し、1年以上保存可能。' },
  { id: 'ox-231', category: '包装', question: 'デガッシング（CO₂放出）が完了する前に真空包装を使用するとパッケージが破損する危険がある。', answer: true, difficulty: 2, explanation: '焙煎直後の豆は大量のCO₂を放出するため、真空包装はCO₂がある程度放出されてから（焙煎後1〜2週間後）使用する。' }
];

