const questionsOX = [
  // コーヒーの歴史・伝播 (10 questions) - 5T, 5F
  { id: 'ox-001', category: 'コーヒーの歴史・伝播', question: 'コーヒーの原産地はエチオピアのカッファ地方である。', answer: true, difficulty: 1, explanation: 'コーヒーノキはエチオピア西部のカッファ地方に自生。「コーヒー」の語源も「カッファ」が転訛したとされている。' },
  { id: 'ox-002', category: 'コーヒーの歴史・伝播', question: 'noble treeはパリ植物園で育てられた苗が起源である。', answer: false, difficulty: 2, explanation: 'noble treeはアムステルダムの植物園で育てられた苗が起源。その後フランス国王ルイ14世に贈られた。' },
  { id: 'ox-003', category: 'コーヒーの歴史・伝播', question: '世界初のコーヒーハウス「カーヴェハーネ」は1554年イスタンブールで開業した。', answer: true, difficulty: 1, explanation: '1554年、オスマン帝国のイスタンブールに世界初のコーヒーハウスが開業した。' },
  { id: 'ox-004', category: 'コーヒーの歴史・伝播', question: 'ヨーロッパ最初のコーヒーハウスはロンドンで1650年に開業した。', answer: false, difficulty: 2, explanation: 'ヨーロッパ最初のコーヒーハウスはベネチア（イタリア）で1645年に開業。イギリス最初はオックスフォードで1650年。' },
  { id: 'ox-005', category: 'コーヒーの歴史・伝播', question: 'ブルボン品種の名前の由来はブルボン島（現レユニオン島）である。', answer: true, difficulty: 2, explanation: 'ティピカの突然変異として生まれたブルボン品種は、フランス領ブルボン島で栽培開始されたことから命名。' },
  { id: 'ox-006', category: 'コーヒーの歴史・伝播', question: 'ラーゼスは12世紀にコーヒーについて医学集成で記述した。', answer: false, difficulty: 2, explanation: 'ラーゼスはアラビアの医師で、900年頃（9〜10世紀）に医学集成で「bunchum」として記述した。' },
  { id: 'ox-007', category: 'コーヒーの歴史・伝播', question: '日本初の珈琲店「可否茶館」は1888年4月13日に東京・上野で開業した。', answer: true, difficulty: 1, explanation: '鄭永慶により1888年（明治21年）4月13日に東京・上野に開業。4月13日は現在「喫茶店の日」。' },
  { id: 'ox-008', category: 'コーヒーの歴史・伝播', question: 'カネフォラ種（ロブスタ）はアフリカのコンゴで1898年に発見された。', answer: true, difficulty: 1, explanation: 'ベルギーの植物学者エミール・ローランがアフリカのコンゴで1898年に発見。' },
  { id: 'ox-009', category: 'コーヒーの歴史・伝播', question: 'オスマン帝国がコーヒー貿易で輸出したのは焙煎豆のみで、生きた種子・苗木は持ち出しを禁止していた。', answer: true, difficulty: 2, explanation: 'オスマン帝国はコーヒーの国際競争力維持のため、焙煎豆のみを輸出し、生きた種子・苗木の持ち出しを禁止（死罪）していた。' },
  { id: 'ox-010', category: 'コーヒーの歴史・伝播', question: 'ロンドンのコーヒーハウスは「ペニー大学」と呼ばれ、1ペニーで利用できた。', answer: false, difficulty: 2, explanation: '1652年のロンドンのコーヒーハウスは1ペニーで利用でき、誰もが気軽に知識を得られることから「ペニー大学」と呼ばれた。実際の説は異なる。' },

  // 植物学的分類・品種 (15 questions) - 8T, 7F
  { id: 'ox-011', category: '植物学的分類・品種', question: 'アラビカ種は他家受粉で繁殖する。', answer: false, difficulty: 1, explanation: 'アラビカ種は自家受粉（自家稔性）で繁殖。カネフォラ種が他家受粉（自家不稔性）。' },
  { id: 'ox-012', category: '植物学的分類・品種', question: 'コーヒーノキの属はコフィア属である。', answer: true, difficulty: 1, explanation: 'コーヒーノキはアカネ目→アカネ科→コーヒーノキ属（コフィア属）に分類される。' },
  { id: 'ox-013', category: '植物学的分類・品種', question: 'カネフォラ種のカフェイン含有量はアラビカ種の約2倍である。', answer: true, difficulty: 2, explanation: 'アラビカ種0.8〜1.4%、カネフォラ種1.7〜4%。カネフォラ種が約2倍高い。' },
  { id: 'ox-014', category: '植物学的分類・品種', question: 'ティピカ品種はアラビカ種の原型である。', answer: true, difficulty: 1, explanation: 'ティピカはアラビカ種の原型で、noble treeもティピカ系。世界に伝播した主要品種。' },
  { id: 'ox-015', category: '植物学的分類・品種', question: 'アラビカ種は2倍体で染色体数は22本である。', answer: false, difficulty: 2, explanation: 'アラビカ種は4倍体で染色体数は44本。カネフォラ種が2倍体で22本。' },
  { id: 'ox-016', category: '植物学的分類・品種', question: 'カトゥーラはブルボンの突然変異から生まれた品種である。', answer: true, difficulty: 2, explanation: 'カトゥーラはブルボンの突然変異で、1935年ブラジルで発見。矮小種で収量が多い。' },
  { id: 'ox-017', category: '植物学的分類・品種', question: 'ゲイシャ品種はパナマが原産地である。', answer: false, difficulty: 2, explanation: 'ゲイシャ品種はエチオピア・ゲシャ村が原産地。パナマで高品質として再注目された。' },
  { id: 'ox-018', category: '植物学的分類・品種', question: 'SL28とSL34はケニアのスコット農業研究所で選抜された品種である。', answer: true, difficulty: 2, explanation: 'SL28・SL34はケニアのスコット農業研究所（Scott Laboratory）で選抜されたさび病耐性品種。' },
  { id: 'ox-019', category: '植物学的分類・品種', question: 'ピーベリーはコーヒーチェリーの約10%に見られる丸い豆である。', answer: false, difficulty: 2, explanation: 'ピーベリーはコーヒーチェリーの約5%に見られる。10%ではなく5%。' },
  { id: 'ox-020', category: '植物学的分類・品種', question: 'コーヒーチェリーの構造は外側から外皮・果肉・ミューシレージ・パーチメント・シルバースキン・種子である。', answer: true, difficulty: 2, explanation: 'コーヒーチェリーは6層構造で外側から：外皮→果肉→ミューシレージ→パーチメント→シルバースキン→種子の順。' },
  { id: 'ox-021', category: '植物学的分類・品種', question: 'ムンドノーボはカトゥーラ×ブルボンの交配品種である。', answer: false, difficulty: 2, explanation: 'ムンドノーボはティピカ×ブルボンの交配品種。カトゥアイがカトゥーラ×ムンドノーボ。' },
  { id: 'ox-022', category: '植物学的分類・品種', question: 'ヒブリドティモール（HdT）はアラビカ×カネフォラの交配品種である。', answer: true, difficulty: 2, explanation: 'ヒブリドティモールはアラビカ×カネフォラの偶発的交配品種で、カネフォラの病害抵抗性を持つ。' },
  { id: 'ox-023', category: '植物学的分類・品種', question: 'マラゴジッペはティピカの突然変異で豆が大粒である。', answer: true, difficulty: 1, explanation: 'マラゴジッペはティピカの突然変異で豆が大粒（エレファントビーン）。ブラジル・マラゴジッペ市で発見。' },
  { id: 'ox-024', category: '植物学的分類・品種', question: 'アラビカ種の少糖類含有量はカネフォラ種より高い。', answer: true, difficulty: 2, explanation: 'アラビカ種6〜9%、カネフォラ種3〜7%。アラビカ種の方が甘み成分が豊富。' },
  { id: 'ox-025', category: '植物学的分類・品種', question: 'コーヒーノキ属には約10種が商業的に流通している。', answer: false, difficulty: 2, explanation: 'コーヒーノキ属には100種以上が確認されているが、商業的に流通するのは主に2種（アラビカ・カネフォラ）。' },

  // 栽培・土壌・病害虫 (15 questions) - 8T, 7F
  { id: 'ox-026', category: '栽培・土壌・病害虫', question: 'コーヒーベルトは南北回帰線の間（北緯25度〜南緯25度）である。', answer: true, difficulty: 1, explanation: 'コーヒーベルトは赤道を挟む南北回帰線（北緯25度〜南緯25度）の間が主要栽培帯。' },
  { id: 'ox-027', category: '栽培・土壌・病害虫', question: 'アラビカ種の最適標高は1,000〜1,500mである。', answer: false, difficulty: 1, explanation: 'アラビカ種の標高は900〜2,000mの範囲。1,000〜1,500mは一部に過ぎない。' },
  { id: 'ox-028', category: '栽培・土壌・病害虫', question: 'アラビカ種に適した土壌の5条件には耕しやすさ・深さ・排水性・肥沃さ・腐植量が含まれる。', answer: true, difficulty: 2, explanation: '5条件：①耕しやすさ（作業性）②土壌の深さ③排水性④肥沃さ⑤腐植の量' },
  { id: 'ox-029', category: '栽培・土壌・病害虫', question: '火山性土壌はコーヒー栽培に適している。理由は排水性が良く、ミネラルが豊富だからである。', answer: true, difficulty: 2, explanation: '火山性土壌はリン・カリウムなどのミネラルが豊富で、排水性と保水性のバランスも良い。' },
  { id: 'ox-030', category: '栽培・土壌・病害虫', question: 'コーヒーさび病は1869年ブラジルで大流行した。', answer: false, difficulty: 2, explanation: 'コーヒーさび病は1869年セイロン島（スリランカ）で大流行（セイロン事件）。ブラジルではない。' },
  { id: 'ox-031', category: '栽培・土壌・病害虫', question: 'コーヒーさび病により1890年までにセイロンの栽培面積の約90%が放棄された。', answer: true, difficulty: 2, explanation: 'セイロン事件：1869年流行→1886年までに輸出量80%減→1890年までに栽培面積90%放棄→紅茶へ転換。' },
  { id: 'ox-032', category: '栽培・土壌・病害虫', question: 'シェードツリーとしてはバナナが最も一般的である。', answer: false, difficulty: 2, explanation: 'シェードツリーとして最も一般的なのはマメ科の樹木（窒素固定木）。バナナは初期の仮設日陰として使用。' },
  { id: 'ox-033', category: '栽培・土壌・病害虫', question: 'コーヒー実穿孔虫（CBB）は世界最大のコーヒー害虫である。', answer: true, difficulty: 2, explanation: 'コーヒー実穿孔虫（Coffee Berry Borer / Hypothenemus hampei）は世界最大のコーヒー害虫で年間5億ドル以上の経済的損失。' },
  { id: 'ox-034', category: '栽培・土壌・病害虫', question: 'コーヒー炭疽病（CBD）は世界中で被害が大きい。', answer: false, difficulty: 2, explanation: 'コーヒー炭疽病は主にアフリカで深刻。ヨーロッパやアジアでは被害が限定的。' },
  { id: 'ox-035', category: '栽培・土壌・病害虫', question: 'コーヒーノキの初開花は定植後2〜4年である。', answer: true, difficulty: 1, explanation: 'コーヒーノキのライフサイクル：定植後2〜4年で初開花が始まる。' },
  { id: 'ox-036', category: '栽培・土壌・病害虫', question: '標高が高いほど、コーヒー豆の成熟がゆっくり進み風味成分が蓄積される。', answer: true, difficulty: 2, explanation: '標高が高い→日較差が大きい→成熟が遅い→風味成分が多く蓄積。高地産ほど硬く酸味・風味が豊か。' },
  { id: 'ox-037', category: '栽培・土壌・病害虫', question: 'クロロゲン酸はコーヒーの苦味・渋味の元である。', answer: true, difficulty: 2, explanation: 'クロロゲン酸はポリフェノールで、生豆では6〜9%含有。焙煎で一部分解される。' },
  { id: 'ox-038', category: '栽培・土壌・病害虫', question: 'アラビカ種の最適気温は年平均18〜22℃である。', answer: true, difficulty: 1, explanation: 'アラビカ種の気温：年平均15〜25℃、最適18〜22℃。' },
  { id: 'ox-039', category: '栽培・土壌・病害虫', question: 'コーヒーさび病の対策として銀系殺菌剤が有効である。', answer: false, difficulty: 2, explanation: 'さび病対策は銅系殺菌剤が有効。銀系ではなく銅系が使用される。' },
  { id: 'ox-040', category: '栽培・土壌・病害虫', question: 'カティモールはカトゥーラ×ヒブリドティモールの交配品種でさび病に強い。', answer: true, difficulty: 2, explanation: 'カティモールはカトゥーラ×ヒブリドティモールの交配品種で、カネフォラの病害抵抗性を持つ。' },

  // 収穫方法 (10 questions) - 5T, 5F
  { id: 'ox-041', category: '収穫方法', question: 'ピッキング方法では同じ畑を複数回巡回して完熟チェリーだけを選んで摘む。', answer: true, difficulty: 1, explanation: 'ピッキング（セレクティブ・ピッキング）は成熟のばらつきに合わせて複数回巡回し、完熟チェリーのみを手で選んで摘む。' },
  { id: 'ox-042', category: '収穫方法', question: 'ストリッピング方法は最もコストが高い。', answer: false, difficulty: 1, explanation: 'ストリッピングはピッキングに比べ大幅に低コスト・短時間。最も高コストはピッキング。' },
  { id: 'ox-043', category: '収穫方法', question: 'コーヒーの開花は乾季後の降雨がトリガーとなる。', answer: true, difficulty: 2, explanation: 'コーヒーノキは乾季の後の降雨をきっかけに開花（降雨後約10〜14日で開花）。' },
  { id: 'ox-044', category: '収穫方法', question: '機械収穫は急斜面・山岳地帯でも使用可能である。', answer: false, difficulty: 1, explanation: '機械収穫は平坦地でのみ使用可能。急斜面・山岳地帯では使用不可。' },
  { id: 'ox-045', category: '収穫方法', question: 'ブラジルはストリッピング方法を採用している。', answer: true, difficulty: 2, explanation: 'ブラジルは平坦地の大規模農園でストリッピング（一斉摘み）を採用。' },
  { id: 'ox-046', category: '収穫方法', question: 'アラビカ種はカネフォラ種より開花・成熟のタイミングが比較的揃いやすい。', answer: true, difficulty: 2, explanation: 'アラビカ種は開花・成熟のタイミングが揃いやすいためピッキングに適している。' },
  { id: 'ox-047', category: '収穫方法', question: 'アラビカ種の開花から完熟までは約6〜9ヶ月である。', answer: true, difficulty: 1, explanation: 'アラビカ種の成熟期間は約6〜9ヶ月（高地では8〜9ヶ月）。' },
  { id: 'ox-048', category: '収穫方法', question: '未熟チェリーは甘い風味を生む。', answer: false, difficulty: 2, explanation: '未熟チェリーは糖分が少なくクロロゲン酸が多いため、渋み・青臭さ・不快な酸味を生む。' },
  { id: 'ox-049', category: '収穫方法', question: 'コロンビアは赤道付近のため年2回の収穫期を持つ。', answer: true, difficulty: 2, explanation: 'コロンビアは赤道付近のため、メインクロップ（10〜2月）とミタカ（3〜6月）の年2回収穫。' },
  { id: 'ox-050', category: '収穫方法', question: 'ケニアの収穫時期は年1回である。', answer: false, difficulty: 2, explanation: 'ケニアは赤道直下のため年2回収穫：メイン3〜7月、フライ9〜12月。' },

  // 精選方法 (20 questions) - 10T, 10F
  { id: 'ox-051', category: '精選方法', question: '非水洗式は設備が不要で廃水も出ない方式である。', answer: true, difficulty: 1, explanation: '非水洗式（ナチュラル）はそのまま乾燥させるため設備が不要で廃水も出ない。' },
  { id: 'ox-052', category: '精選方法', question: '水洗式は大量の水が必要である。', answer: true, difficulty: 1, explanation: '水洗式は水比重選別・発酵槽・水洗いで大量の水が必要。廃水問題も課題。' },
  { id: 'ox-053', category: '精選方法', question: 'パルプドナチュラル方法はミューシレージを完全に除去する。', answer: false, difficulty: 2, explanation: 'パルプドナチュラルはミューシレージを残したまま乾燥させる。除去は水洗式。' },
  { id: 'ox-054', category: '精選方法', question: 'スマトラ式は乾燥期間が短縮される特徴がある。', answer: true, difficulty: 2, explanation: 'スマトラ式は半生きの状態で脱殻するため乾燥期間が短縮（約3日）。ウォッシュドの1〜2週間と比較。' },
  { id: 'ox-055', category: '精選方法', question: 'ナチュラル精選では未成熟果実を乾燥前に取り除く必要がある。', answer: false, difficulty: 2, explanation: 'ナチュラル精選は未成熟果実を乾燥前に取り除けないが、パルプドナチュラルはパルパーで除去可能。' },
  { id: 'ox-056', category: '精選方法', question: 'ケニア式はダブルウォッシュド方式で非常にクリーンなカップになる。', answer: true, difficulty: 2, explanation: 'ケニア式は発酵→水洗い→再発酵→最終水洗いで非常にクリーンなカップになる。' },
  { id: 'ox-057', category: '精選方法', question: 'ハニーコーヒーのブラックはミューシレージの残存率が最も低い。', answer: false, difficulty: 2, explanation: 'ハニーコーヒーの残存率順：ブラック＞レッド＞イエロー＞ホワイト。ホワイトが最も低い。' },
  { id: 'ox-058', category: '精選方法', question: 'スマトラ式はミューシレージ付きのパーチメント状態で脱殻する。', answer: true, difficulty: 2, explanation: 'スマトラ式の特徴は半生きの状態（水分30〜35%）で脱殻すること。' },
  { id: 'ox-059', category: '精選方法', question: 'アナエロビック発酵は密閉タンクに酸素を充填する。', answer: false, difficulty: 2, explanation: 'アナエロビック発酵はCO₂を充填し酸素を遮断する。酸素ではなく二酸化炭素。' },
  { id: 'ox-060', category: '精選方法', question: 'カーボニックマセレーションはチェリーを丸ごと密閉容器に入れる。', answer: true, difficulty: 2, explanation: 'カーボニックマセレーションはチェリーが果肉付きのままで、CO₂を能動的に注入する方法。' },
  { id: 'ox-061', category: '精選方法', question: '非水洗式コーヒーは風味が淡白である。', answer: false, difficulty: 2, explanation: '非水洗式は果実の甘み・ボディが豊かな風味を生む。淡白なのは水洗式。' },
  { id: 'ox-062', category: '精選方法', question: 'ナチュラル精選の課題は乾燥に時間がかかることである。', answer: true, difficulty: 2, explanation: 'ナチュラル精選は乾燥に時間がかかり、腐敗リスクもある課題がある。' },
  { id: 'ox-063', category: '精選方法', question: 'ブラジルが開発地のパルプドナチュラル方法はコスタリカでも盛んである。', answer: true, difficulty: 2, explanation: 'パルプドナチュラルはブラジルが開発地だが、コスタリカでもハニープロセスとして盛んに実施。' },
  { id: 'ox-064', category: '精選方法', question: 'スマトラ式生豆は深緑色で形がいびつになりやすい。', answer: true, difficulty: 2, explanation: 'スマトラ式は半生きの状態で脱殻するため、生豆が独特の深緑色でいびつになりやすい。' },
  { id: 'ox-065', category: '精選方法', question: 'ウォッシュド精選により品質が均一化されやすい。', answer: true, difficulty: 1, explanation: '水洗式は水比重選別や発酵槽で異物・未熟豆を除去でき、品質が均一化されやすい。' },
  { id: 'ox-066', category: '精選方法', question: 'インドネシア・スマトラ島ではナチュラル精選が主流である。', answer: false, difficulty: 2, explanation: 'インドネシア・スマトラ島ではスマトラ式（ウェットハル / ギリンバサ）が独自方式。ナチュラルではない。' },
  { id: 'ox-067', category: '精選方法', question: 'コロンビアの水洗式はクリーンで明確な酸味が特徴である。', answer: true, difficulty: 2, explanation: '水洗式は未成熟果実を除去でき、クリーン・明確な酸味が特徴になる。' },
  { id: 'ox-068', category: '精選方法', question: 'ケニア式発酵は1回のみである。', answer: false, difficulty: 2, explanation: 'ケニア式（ダブルウォッシュド）は2回の発酵：①12〜24時間→②再度12〜24時間。' },
  { id: 'ox-069', category: '精選方法', question: 'イエメンはナチュラル精選を伝統的に採用している。', answer: true, difficulty: 2, explanation: 'イエメンは非水洗式（ナチュラル）で伝統的な天日乾燥を実施。' },
  { id: 'ox-070', category: '精選方法', question: 'エチオピアは水洗式のみを採用している。', answer: false, difficulty: 2, explanation: 'エチオピアは非水洗式と水洗式の両方を採用。地域や施設により異なる。' },

  // 選別方法 (10 questions) - 5T, 5F
  { id: 'ox-071', category: '選別方法', question: '1スクリーンは1/64インチである。', answer: true, difficulty: 1, explanation: '1スクリーン = 1/64インチ ≒ 約0.4mm。スクリーン18 = 18/64インチ ≒ 約7.1mm。' },
  { id: 'ox-072', category: '選別方法', question: 'コロンビアの格付けでSupremoはスクリーン18以上である。', answer: false, difficulty: 2, explanation: 'コロンビアSupremo = SC17以上、Excelso = SC14〜16。18以上ではなく17以上が正しい。' },
  { id: 'ox-073', category: '選別方法', question: 'ブラジルの格付けでNo.1が最高品質である。', answer: false, difficulty: 2, explanation: 'ブラジルはNo.2が最高グレード。No.1は存在しない（完全無欠点は不可能という考え方）。' },
  { id: 'ox-074', category: '選別方法', question: 'ケニアの格付けでAAはスクリーン17〜18である。', answer: true, difficulty: 2, explanation: 'ケニアAA = SC17〜18（7.22mm以上）。AB = SC15〜16。' },
  { id: 'ox-075', category: '選別方法', question: '比重選別は密度による豆の分離である。', answer: true, difficulty: 1, explanation: '比重選別は傾斜した振動テーブルで密度差により分離。重い豆は上方へ、軽い豆は下方へ。' },
  { id: 'ox-076', category: '選別方法', question: '電子選別は色と形状を高速識別する。', answer: false, difficulty: 2, explanation: '電子選別はカメラ・レーザーセンサーで色を高速識別し、エアジェットで弾き飛ばす。形状ではなく色が主対象。' },
  { id: 'ox-077', category: '選別方法', question: 'ピーベリーはサイズが通常の豆より小さい。', answer: false, difficulty: 2, explanation: 'ピーベリーはサイズは通常の豆より小さいというわけではなく、形が丸いことで区別される。品質は優れるわけではない。' },
  { id: 'ox-078', category: '選別方法', question: 'スペシャルティコーヒー基準ではカテゴリー1欠点は0個が条件である。', answer: true, difficulty: 2, explanation: 'SCAスペシャルティグレードはカテゴリー1欠点（重大欠点）0個、カテゴリー2欠点5個以内。' },
  { id: 'ox-079', category: '選別方法', question: 'エチオピアはスクリーンサイズ方式で格付けしている。', answer: false, difficulty: 2, explanation: 'エチオピアは欠点数方式（G1〜G5）で格付け。スクリーンサイズ方式はコロンビア・ケニア。' },
  { id: 'ox-080', category: '選別方法', question: 'ハンドピックは最終工程として行われ、最も精度が高い選別方法である。', answer: true, difficulty: 1, explanation: 'ハンドピック（手選別）は最終工程として行われ、人の目で最後のチェックを行う最も精度が高い方法。' },

  // 生豆の成分 (15 questions) - 8T, 7F
  { id: 'ox-081', category: '生豆の成分', question: 'カフェインは焙煎で大幅に減少する。', answer: false, difficulty: 2, explanation: 'カフェインはほとんど変化しない。減少するのはショ糖・クロロゲン酸・アミノ酸。' },
  { id: 'ox-082', category: '生豆の成分', question: 'ショ糖は焙煎でカラメル化・メイラード反応の原料として消費される。', answer: true, difficulty: 2, explanation: 'ショ糖（少糖類）は焙煎で大幅に減少。カラメル化・メイラード反応に使用される。' },
  { id: 'ox-083', category: '生豆の成分', question: 'クロロゲン酸は6〜9%含有され、焙煎で一部分解される。', answer: true, difficulty: 2, explanation: 'クロロゲン酸はアラビカ種5〜8%、カネフォラ種7〜10%。焙煎で一部分解。' },
  { id: 'ox-084', category: '生豆の成分', question: 'トリゴネリンはニコチン酸（ビタミンB3）に分解される。', answer: true, difficulty: 2, explanation: 'トリゴネリンは焙煎でニコチン酸（ナイアシン＝ビタミンB3）に分解。' },
  { id: 'ox-085', category: '生豆の成分', question: 'アラビカ種の脂質含有量はカネフォラ種より高い。', answer: true, difficulty: 2, explanation: 'アラビカ種12〜18%、カネフォラ種9〜13%。アラビカ種の方が脂質が多い。' },
  { id: 'ox-086', category: '生豆の成分', question: '多糖類は焙煎による変化が比較的大きい。', answer: false, difficulty: 2, explanation: '多糖類（セルロース・ヘミセルロース）は焙煎による変化が比較的小さい。' },
  { id: 'ox-087', category: '生豆の成分', question: 'メイラード反応はアミノ酸＋少糖類で約150℃以上で開始される。', answer: true, difficulty: 2, explanation: 'メイラード反応は褐色色素と香気成分を生成し、約150℃以上で開始。' },
  { id: 'ox-088', category: '生豆の成分', question: '有機酸はコーヒーの酸味の基であり、焙煎で全て分解される。', answer: false, difficulty: 2, explanation: '有機酸は焙煎で一部分解、一部は生成される。全て分解されるわけではない。' },
  { id: 'ox-089', category: '生豆の成分', question: 'コーヒーオイル（脂質）はペーパーフィルターで除去されない。', answer: false, difficulty: 2, explanation: 'コーヒーオイルはペーパーフィルターで除去される。金属フィルターより味への影響が減少。' },
  { id: 'ox-090', category: '生豆の成分', question: '焙煎で生成される香気成分は約800〜1000種類以上である。', answer: true, difficulty: 2, explanation: '現在の分析では焙煎で800〜1000種類以上の香気成分が生成される。' },
  { id: 'ox-091', category: '生豆の成分', question: 'アミノ酸は焙煎で増加する。', answer: false, difficulty: 2, explanation: 'アミノ酸はメイラード反応に使用されるため焙煎で減少。増加しない。' },
  { id: 'ox-092', category: '生豆の成分', question: 'アラビカ種のトリゴネリン含有量はカネフォラ種より高い。', answer: true, difficulty: 2, explanation: 'アラビカ種0.6〜1.3%、カネフォラ種0.3〜0.9%。アラビカ種の方が高い。' },
  { id: 'ox-093', category: '生豆の成分', question: '水分は焙煎で約5〜10%減少する。', answer: false, difficulty: 2, explanation: '水分は焙煎で約15〜20%減少（大幅に減少）。5〜10%ではなく15〜20%。' },
  { id: 'ox-094', category: '生豆の成分', question: 'アラビカ種の少糖類含有量は6〜9%である。', answer: true, difficulty: 1, explanation: 'アラビカ種の少糖類は6〜9%、カネフォラ種は3〜7%。焙煎でメイラード反応の原料になる。' },
  { id: 'ox-095', category: '生豆の成分', question: 'ペーパーフィルターはカフェストールも除去する。', answer: true, difficulty: 2, explanation: 'ペーパーフィルターはコーヒーオイル・微粉・カフェストールを除去。金属フィルターは通す。' },

  // 焙煎 (20 questions) - 10T, 10F
  { id: 'ox-096', category: '焙煎', question: '直火式焙煎機はシリンダーの真下に熱源があり穴あきシリンダーを使う。', answer: true, difficulty: 2, explanation: '直火式は熱源がシリンダー真下で穴あきシリンダー。輻射熱が豆に直接当たる。' },
  { id: 'ox-097', category: '焙煎', question: '熱風式焙煎機は熱源がシリンダーの真下にある。', answer: false, difficulty: 2, explanation: '熱風式は熱源が離れた位置にあり、加熱した空気をシリンダーに引き込む方式。' },
  { id: 'ox-098', category: '焙煎', question: '1ハゼは約180〜200℃で発生し豆が膨らみ始める。', answer: true, difficulty: 2, explanation: '1ハゼ（ファーストクラック）は約180〜200℃で「パチパチ」という音が鳴り豆が膨張。' },
  { id: 'ox-099', category: '焙煎', question: '2ハゼは約150〜170℃で油脂が表面に出てくる。', answer: false, difficulty: 2, explanation: '2ハゼ（セカンドクラック）は約220〜230℃で「チチチ」という音が鳴り油脂が表面に出る。' },
  { id: 'ox-100', category: '焙煎', question: '焙煎により豆の体積は約1.5〜2倍に膨張する。', answer: true, difficulty: 2, explanation: '焙煎により内部のCO₂・水蒸気で体積は約1.5〜2倍に膨張。' },
  { id: 'ox-101', category: '焙煎', question: '焙煎により豆の重量は約30%減少する。', answer: false, difficulty: 2, explanation: '焙煎により豆の重量は約15〜20%減少（水分蒸発）。30%ではなく15〜20%。' },
  { id: 'ox-102', category: '焙煎', question: 'ハイローストは最もスタンダードな焙煎度である。', answer: true, difficulty: 1, explanation: '焙煎度8段階：①ライト②シナモン③ミディアム④ハイ⑤シティ⑥フルシティ⑦フレンチ⑧イタリアン。ハイが④でスタンダード。' },
  { id: 'ox-103', category: '焙煎', question: 'ベイクドは長時間低温で焙煎しすぎた欠陥である。', answer: true, difficulty: 2, explanation: 'ベイクドは長時間低温焙煎による欠陥で、平坦な風味・甘みの欠如が特徴。' },
  { id: 'ox-104', category: '焙煎', question: 'スコーチは豆内部の未発達が原因である。', answer: false, difficulty: 2, explanation: 'スコーチは豆の表面だけが高温になる欠陥で、焦げ臭・苦味過多が生じる。未発達ではなく表面過熱が原因。' },
  { id: 'ox-105', category: '焙煎', question: 'ティッピングは豆の先端が焦げる欠陥である。', answer: true, difficulty: 2, explanation: 'ティッピングは豆の先端が焦げる欠陥で、焦げ味が混入。' },
  { id: 'ox-106', category: '焙煎', question: 'シナモンローストは薄茶色で高酸味が特徴である。', answer: true, difficulty: 1, explanation: 'シナモンは焙煎度2で薄茶色、高酸味が特徴の浅煎り。' },
  { id: 'ox-107', category: '焙煎', question: 'フレンチローストはイタリアンより浅い焙煎である。', answer: true, difficulty: 1, explanation: '焙煎度順：⑦フレンチ＜⑧イタリアン。フレンチの方がイタリアンより浅い。' },
  { id: 'ox-108', category: '焙煎', question: '輻射熱は電磁波を介して熱移動が発生する。', answer: true, difficulty: 2, explanation: '輻射（放射）は空間を介して隔てられた2つの物体表面間で電磁波による熱移動。' },
  { id: 'ox-109', category: '焙煎', question: '対流は流体の移動による熱移動である。', answer: true, difficulty: 2, explanation: '対流は流体（気体・液体）の移動による熱移動。焙煎では熱風による表面加熱。' },
  { id: 'ox-110', category: '焙煎', question: '伝導は豆の内部および豆同士の接触による熱移動である。', answer: true, difficulty: 2, explanation: '伝導は固体内の熱移動。焙煎では豆内部・豆同士・ドラムとの接触での熱移動。' },
  { id: 'ox-111', category: '焙煎', question: 'シティローストは中深煎りでバランスが良い。', answer: true, difficulty: 1, explanation: 'シティは焙煎度5で中深煎り、バランスが良い焙煎度。' },
  { id: 'ox-112', category: '焙煎', question: 'フルシティは2ハゼ後半の深煎りである。', answer: true, difficulty: 2, explanation: 'フルシティは焙煎度6で深煎り、2ハゼ後半の焙煎度。' },
  { id: 'ox-113', category: '焙煎', question: 'ミディアムローストは中煎りでスタンダードである。', answer: false, difficulty: 1, explanation: 'ミディアムは焙煎度3で浅煎り。スタンダードはハイ（焙煎度4）。' },
  { id: 'ox-114', category: '焙煎', question: '焙煎中に大量の二酸化炭素が生成される。', answer: true, difficulty: 2, explanation: '焙煎により豆内の二酸化炭素が大量に生成される。焙煎後のデガッシングで徐々に放出。' },
  { id: 'ox-115', category: '焙煎', question: 'イタリアンローストは最深煎りで炭化に近い。', answer: true, difficulty: 1, explanation: 'イタリアンは焙煎度8で最深煎り、炭化に近い焙煎度。' },

  // 粉砕・包装・保管 (10 questions) - 5T, 5F
  { id: 'ox-116', category: '粉砕・包装・保管', question: 'カッティング式（臼刃式）グラインダーは粒度が均一になりやすい。', answer: true, difficulty: 2, explanation: 'カッティング式は2枚の刃で豆を切削し粒度が均一。フラット刃とコニカル刃がある。' },
  { id: 'ox-117', category: '粉砕・包装・保管', question: 'ブレード式グラインダーは粒度が均一である。', answer: false, difficulty: 1, explanation: 'ブレード式（プロペラ式）は粒度が不均一。カッティング式が均一。' },
  { id: 'ox-118', category: '粉砕・包装・保管', question: '粉砕後のコーヒーは酸化・劣化が急速に進む。', answer: true, difficulty: 2, explanation: '粉砕により表面積が増大し、酸化・劣化が急速に進む。CO₂の放出も加速。' },
  { id: 'ox-119', category: '粉砕・包装・保管', question: 'バルブ付き包装はCO₂を排出するワンウェイバルブである。', answer: true, difficulty: 2, explanation: 'バルブ付き包装はCO₂を外に逃がし、酸素を遮断するワンウェイバルブ付き。' },
  { id: 'ox-120', category: '粉砕・包装・保管', question: '真空包装は焙煎直後から使用できる。', answer: false, difficulty: 2, explanation: '真空包装はCO₂が落ち着いてから使用。焙煎直後はバルブ付き包装を使用。' },
  { id: 'ox-121', category: '粉砕・包装・保管', question: 'コーヒーの劣化原因は酸素・水分・高温・光である。', answer: true, difficulty: 1, explanation: 'コーヒー劣化の4大敵：①酸素（酸化）②水分（湿気）③高温④光（紫外線）' },
  { id: 'ox-122', category: '粉砕・包装・保管', question: '生豆の適正水分含有率は15〜20%である。', answer: false, difficulty: 2, explanation: '生豆の適正水分含有率は10〜12%以下（脱殻後の目安）。15〜20%ではなく10〜12%。' },
  { id: 'ox-123', category: '粉砕・包装・保管', question: 'ガス置換包装は窒素で酸化防止効果を高める。', answer: true, difficulty: 2, explanation: 'ガス置換包装（窒素充填）は袋内の空気を窒素で置換し酸化防止効果を高める。' },
  { id: 'ox-124', category: '粉砕・包装・保管', question: 'デガッシングはCO₂が放出される過程である。', answer: true, difficulty: 2, explanation: 'デガッシング（脱気）は焙煎直後から数日〜数週間かけてCO₂が徐々に放出される。' },
  { id: 'ox-125', category: '粉砕・包装・保管', question: '1コンテナ（20フィート）のコーヒー搭載量は通常1〜3トンである。', answer: false, difficulty: 2, explanation: '1コンテナ搭載量は通常15〜18トン程度（60kg袋）。1〜3トンではなく15〜18トン。' },

  // 産地・格付け・流通 (15 questions) - 8T, 7F
  { id: 'ox-126', category: '産地・格付け・流通', question: 'ブラジルは世界最大のコーヒー生産国で世界シェア約35〜38%である。', answer: true, difficulty: 1, explanation: 'ブラジルは生産量1位でシェア約35〜38%。2位ベトナム（15〜17%）、3位コロンビア（7〜8%）。' },
  { id: 'ox-127', category: '産地・格付け・流通', question: 'コロンビアの格付けは欠点数方式である。', answer: false, difficulty: 1, explanation: 'コロンビアはスクリーンサイズ方式（Supremo/Excelso）。ブラジルが欠点数方式。' },
  { id: 'ox-128', category: '産地・格付け・流通', question: 'グアテマラはSHB（標高1,350m以上）でスクリーンサイズ方式である。', answer: false, difficulty: 2, explanation: 'グアテマラはSHB標高1,350m以上で標高方式を採用。スクリーンサイズ方式ではない。' },
  { id: 'ox-129', category: '産地・格付け・流通', question: 'ケニアはスクリーンサイズとカップテストの複合方式で格付けしている。', answer: true, difficulty: 2, explanation: 'ケニアはAA（SC17〜18）等スクリーン＋カップテストの複合方式。' },
  { id: 'ox-130', category: '産地・格付け・流通', question: 'エチオピアの格付けはG1（0〜3個欠点）からG5（46〜90個欠点）である。', answer: true, difficulty: 2, explanation: 'エチオピアは欠点数方式で300gサンプルでG1〜G5に分類。' },
  { id: 'ox-131', category: '産地・格付け・流通', question: 'ブルーマウンテンはジャマイカのブルーマウンテン地区産アラビカ種である。', answer: true, difficulty: 1, explanation: 'ブルーマウンテンはジャマイカ・ブルーマウンテン地区産アラビカ種。日本が最大輸入国。' },
  { id: 'ox-132', category: '産地・格付け・流通', question: 'コスタリカはロブスタ種の栽培を法律で禁止している。', answer: true, difficulty: 2, explanation: 'コスタリカは法律によりロブスタ種の栽培を禁止。アラビカ種のみ。' },
  { id: 'ox-133', category: '産地・格付け・流通', question: 'ハワイはアメリカ唯一の商業的コーヒー産地である。', answer: true, difficulty: 2, explanation: 'ハワイ島コナ地区はアメリカ合衆国唯一の商業的コーヒー産地。' },
  { id: 'ox-134', category: '産地・格付け・流通', question: 'インドの「モンスーニング」はモンスーンの乾いた風にさらして熟成させる。', answer: false, difficulty: 2, explanation: 'モンスーニングはモンスーンの湿った風にさらして熟成。乾いた風ではなく湿った風。' },
  { id: 'ox-135', category: '産地・格付け・流通', question: 'モカはイエメンのモカ港に由来する名称である。', answer: true, difficulty: 1, explanation: 'モカはイエメンのモカ港に由来。イエメン産またはエチオピア産。' },
  { id: 'ox-136', category: '産地・格付け・流通', question: 'ICOは1963年に設立された国際コーヒー機関である。', answer: true, difficulty: 2, explanation: 'ICO（International Coffee Organization）は1963年にロンドンで設立。' },
  { id: 'ox-137', category: '産地・格付け・流通', question: 'ベトナムはカネフォラ種（ロブスタ）が約95%である。', answer: true, difficulty: 2, explanation: 'ベトナムはカネフォラ種が約95%で、世界2位の生産国。主にインスタント・ブレンド用。' },
  { id: 'ox-138', category: '産地・格付け・流通', question: 'タンザニアのキリマンジャロは標高方式で格付けされている。', answer: false, difficulty: 2, explanation: 'タンザニアはスクリーンサイズ＋カップテスト方式。標高方式はグアテマラ等。' },
  { id: 'ox-139', category: '産地・格付け・流通', question: 'マンデリンはインドネシア・スマトラ島北部産のアラビカ種である。', answer: true, difficulty: 1, explanation: 'マンデリンはインドネシア・スマトラ島北部産。スマトラ式精選で深緑色が特徴。' },
  { id: 'ox-140', category: '産地・格付け・流通', question: 'コロンビアは年2回の収穫期を持つ。', answer: true, difficulty: 2, explanation: 'コロンビアはメインクロップ（10〜2月）とミタカ（3〜6月）の年2回収穫。' },

  // 抽出・品質管理 (10 questions) - 5T, 5F
  { id: 'ox-141', category: '抽出・品質管理', question: 'SCA方式のカッピングは粉8.25gに湯150mlを使用する。', answer: true, difficulty: 2, explanation: 'SCA方式：粉8.25g（±0.25g）、湯150ml、湯温93℃±1℃、4分間浸漬。' },
  { id: 'ox-142', category: '抽出・品質管理', question: '抽出率の適正範囲は18〜22%である。', answer: true, difficulty: 2, explanation: '適正抽出率は18〜22%。18%未満は未抽出、22%超過は過抽出。' },
  { id: 'ox-143', category: '抽出・品質管理', question: 'ドリップコーヒーのTDS目安は1.15〜1.35%である。', answer: true, difficulty: 2, explanation: 'TDS（Total Dissolved Solids）ドリップ目安：1.15〜1.35%（11.5〜13.5g/L）。' },
  { id: 'ox-144', category: '抽出・品質管理', question: 'ペーパーフィルターはコーヒーオイルを除去する。', answer: true, difficulty: 1, explanation: 'ペーパーフィルターはコーヒーオイル・微粉・カフェストールを除去。金属フィルターは通す。' },
  { id: 'ox-145', category: '抽出・品質管理', question: 'ドリップのコーヒーと水の比率は粉1に対して水15〜18である。', answer: true, difficulty: 2, explanation: 'ドリップのブリューレシオ：粉1に対して水15〜18（例：粉15gに湯250ml）。' },
  { id: 'ox-146', category: '抽出・品質管理', question: '黒豆の欠点は発酵臭・腐敗臭を生む。', answer: true, difficulty: 1, explanation: '黒豆（デッドビーン）は過熟・腐敗・過度の発酵で、発酵臭・腐敗臭が生じる。' },
  { id: 'ox-147', category: '抽出・品質管理', question: '未熟豆は甘い風味を生む。', answer: false, difficulty: 1, explanation: '未熟豆は糖分が少ないため渋み・青臭さ・不快な酸味を生む。甘くない。' },
  { id: 'ox-148', category: '抽出・品質管理', question: 'SCAのカッピング評価項目は11項目である。', answer: true, difficulty: 2, explanation: 'SCAカッピングは採点項目7+存在確認項目3+減点項目1=計11項目。' },
  { id: 'ox-149', category: '抽出・品質管理', question: '理想的な湯硬度は150〜300ppm程度の軟水〜中硬水である。', answer: true, difficulty: 2, explanation: '抽出に影響する湯硬度（ミネラル分）の理想値は150〜300ppm程度の軟水〜中硬水。' },
  { id: 'ox-150', category: '抽出・品質管理', question: 'SCAブレイキングはクラスト（表面の粉の層）を5回かき分ける。', answer: false, difficulty: 2, explanation: 'SCAブレイキングはクラストを3回かき分ける。5回ではなく3回が正しい。' },

  // Advanced Difficulty 3 Questions (ox-151 to ox-170)
  // 焙煎 (5 questions)
  { id: 'ox-151', category: '焙煎', question: '焙煎により豆の体積は約1.5〜2倍に膨張する。', answer: true, difficulty: 3, explanation: '焙煎により内部のCO₂・水蒸気で豆の体積は約1.5〜2倍に膨張する。これが焙煎による物理的変化の一つ。' },
  { id: 'ox-152', category: '焙煎', question: '直火式焙煎機は輻射熱が豆に直接当たる方式である。', answer: true, difficulty: 3, explanation: '直火式は熱源がシリンダーの真下にあり、穴あきシリンダーを使用するため輻射熱が豆に直接当たる。' },
  { id: 'ox-153', category: '焙煎', question: '焙煎により豆の重量は約25〜30%減少する。', answer: false, difficulty: 3, explanation: '焙煎により豆の重量は約15〜20%減少する。25〜30%は多すぎる。数字の微細な違いが出題される。' },
  { id: 'ox-154', category: '焙煎', question: '焙煎中に生成される香気成分は約500〜700種類である。', answer: false, difficulty: 3, explanation: '焙煎で生成される香気成分は約800〜1000種類以上。500〜700では少なすぎる。' },
  { id: 'ox-155', category: '焙煎', question: '2ハゼは約190〜210℃で発生する。', answer: false, difficulty: 3, explanation: '2ハゼは約220〜230℃で発生する。190〜210℃は低すぎる。わずかな数字の違いが試験に出題される。' },

  // 産地・格付け・流通 (5 questions)
  { id: 'ox-156', category: '産地・格付け・流通', question: 'ブラジルはスクリーンサイズと欠点数方式の複合方式で格付けしている。', answer: true, difficulty: 3, explanation: 'ブラジルの格付けはNo.2（最高）〜No.8と欠点数方式、またスクリーン17/18以上がFineという複合方式。' },
  { id: 'ox-157', category: '産地・格付け・流通', question: 'グアテマラの標高方式ではSHBが1,200m以上の栽培地を示す。', answer: false, difficulty: 3, explanation: 'グアテマラのSHB（Strictly Hard Bean）は標高1,350m以上。1,200mではなく1,350m以上が正確。' },
  { id: 'ox-158', category: '産地・格付け・流通', question: 'タンザニアのキリマンジャロは標高方式のみで格付けされている。', answer: false, difficulty: 3, explanation: 'タンザニアはスクリーンサイズ＋カップテストの複合方式で格付け。標高方式ではない。' },
  { id: 'ox-159', category: '産地・格付け・流通', question: 'インドのモンスーンマラバールはモンスーニング処理により独特のまろやかさと低酸味が特徴である。', answer: true, difficulty: 3, explanation: 'モンスーニングはモンスーンの湿った風にさらして熟成。モンスーンマラバールはインド産コーヒーの代表的ブランド。' },
  { id: 'ox-160', category: '産地・格付け・流通', question: 'ベトナムはアラビカ種が約95%を占める主要産地である。', answer: false, difficulty: 3, explanation: 'ベトナムはカネフォラ種（ロブスタ）が約95%。アラビカではなくカネフォラが主流。' },

  // 抽出・品質管理 (5 questions)
  { id: 'ox-161', category: '抽出・品質管理', question: 'SCA方式のカッピングは4分間浸漬した後にクラストを3回かき分ける。', answer: true, difficulty: 3, explanation: 'SCA方式は粉8.25gに湯150mlで4分間浸漬後、クラスト（表面の粉層）を3回かき分ける。5回ではなく3回が正確。' },
  { id: 'ox-162', category: '抽出・品質管理', question: '抽出率が18%未満の場合は未抽出で酸味が際立つ傾向がある。', answer: true, difficulty: 3, explanation: '適正抽出率は18〜22%。18%未満は未抽出で酸味が際立つ・薄い・未発達な風味が特徴。22%超過は過抽出で苦味が強い。' },
  { id: 'ox-163', category: '抽出・品質管理', question: 'ドリップコーヒーのTDS目安は1.20〜1.40%である。', answer: false, difficulty: 3, explanation: 'TDS目安は1.15〜1.35%（11.5〜13.5g/L）。1.20〜1.40%は範囲がズレている。' },
  { id: 'ox-164', category: '抽出・品質管理', question: 'ドリップのコーヒーと水の比率は粉1に対して水16〜19が理想的である。', answer: false, difficulty: 3, explanation: 'ドリップのブリューレシオは粉1に対して水15〜18。16〜19では上限が高すぎる。' },
  { id: 'ox-165', category: '抽出・品質管理', question: 'スペシャルティコーヒーはカテゴリー1欠点が1個まで許容される。', answer: false, difficulty: 3, explanation: 'スペシャルティグレードはカテゴリー1欠点は0個が条件。1個でも許容されない。' },

  // 精選方法 (3 questions)
  { id: 'ox-166', category: '精選方法', question: 'パルプドナチュラルはブラジルが開発地で、果肉を除去した後ミューシレージを残したまま乾燥する。', answer: true, difficulty: 3, explanation: 'パルプドナチュラルはブラジルが開発地。パルパーで果肉は除去するがミューシレージは残して乾燥。ハニープロセスとも呼ばれる。' },
  { id: 'ox-167', category: '精選方法', question: 'スマトラ式は完全に乾燥した状態で脱殻される。', answer: false, difficulty: 3, explanation: 'スマトラ式の最大の特徴は半生きの状態（水分30〜35%）で脱殻すること。完全乾燥ではなく半乾き状態が特徴。' },
  { id: 'ox-168', category: '精選方法', question: 'ナチュラル精選は乾燥前に未成熟果実を機械で効率的に除去できる。', answer: false, difficulty: 3, explanation: 'ナチュラル精選は未成熟果実を乾燥前に取り除けない。パルプドナチュラルやウォッシュドで機械除去可能。' },

  // 生豆の成分 (2 questions)
  { id: 'ox-169', category: '生豆の成分', question: '水分は焙煎で約15〜20%減少する。', answer: true, difficulty: 3, explanation: '水分は焙煎で約15〜20%減少する。これは大幅な減少。12〜15%では少なすぎる。' },
  { id: 'ox-170', category: '生豆の成分', question: 'ショ糖は焙煎中にカラメル化・メイラード反応の原料として大幅に減少する。', answer: true, difficulty: 3, explanation: 'ショ糖（少糖類）は焙煎で大幅に減少し、カラメル化とメイラード反応によりコーヒー色と香りが生成される。' }
];

